/*
 * JBoss, Home of Professional Open Source
 * Copyright 2014 Red Hat Inc. and/or its affiliates and other contributors
 * as indicated by the @authors tag. All rights reserved.
 * See the copyright.txt in the distribution for a
 * full listing of individual contributors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * http://www.apache.org/licenses/LICENSE-2.0
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.aesh.processor;

import java.util.ArrayList;
import java.util.List;

import javax.lang.model.element.AnnotationMirror;
import javax.lang.model.element.AnnotationValue;
import javax.lang.model.element.ExecutableElement;
import javax.lang.model.element.TypeElement;
import javax.lang.model.element.VariableElement;
import javax.lang.model.type.DeclaredType;
import javax.lang.model.type.TypeKind;
import javax.lang.model.type.TypeMirror;
import javax.lang.model.util.Elements;
import javax.lang.model.util.Types;

import org.aesh.command.CommandDefinition;
import org.aesh.command.GroupCommandDefinition;
import org.aesh.command.option.Argument;
import org.aesh.command.option.Arguments;
import org.aesh.command.option.Mixin;
import org.aesh.command.option.Option;
import org.aesh.command.option.OptionGroup;
import org.aesh.command.option.OptionList;
import org.aesh.command.option.ParentCommand;

/**
 * Generates Java source code for {@code CommandMetadataProvider} implementations.
 *
 * @author Aesh team
 */
final class CodeGenerator {

    // Sentinel class names — when annotation value equals these, skip the builder call
    private static final String NULL_COMMAND_VALIDATOR = "org.aesh.command.impl.validator.NullCommandValidator";
    private static final String NULL_RESULT_HANDLER = "org.aesh.command.impl.result.NullResultHandler";
    private static final String NULL_COMMAND_ACTIVATOR = "org.aesh.command.impl.activator.NullCommandActivator";
    private static final String NULL_OPTION_COMPLETER = "org.aesh.command.impl.completer.NullOptionCompleter";
    private static final String NULL_CONVERTER = "org.aesh.command.impl.converter.NullConverter";
    private static final String NULL_VALIDATOR = "org.aesh.command.impl.validator.NullValidator";
    private static final String NULL_ACTIVATOR = "org.aesh.command.impl.activator.NullActivator";
    private static final String NULL_OPTION_RENDERER = "org.aesh.command.impl.renderer.NullOptionRenderer";
    private static final String AESH_OPTION_PARSER = "org.aesh.command.impl.parser.AeshOptionParser";
    private static final String NULL_DEFAULT_VALUE_PROVIDER = "org.aesh.command.impl.provider.NullDefaultValueProvider";
    private static final String NULL_HELP_SECTION_PROVIDER = "org.aesh.command.impl.provider.NullHelpSectionProvider";

    private CodeGenerator() {
    }

    static String generate(
            String packageName, String simpleName, String metadataClassName,
            String qualifiedCommandName, TypeElement commandElement,
            List<VariableElement> fields, boolean isGroup,
            Elements elementUtils, Types typeUtils) {

        StringBuilder sb = new StringBuilder();

        // Package
        if (!packageName.isEmpty()) {
            sb.append("package ").append(packageName).append(";\n\n");
        }

        // Imports
        sb.append("import java.util.Arrays;\n\n");
        sb.append("import org.aesh.command.Command;\n");
        sb.append("import org.aesh.command.impl.internal.ProcessedCommand;\n");
        sb.append("import org.aesh.command.impl.internal.ProcessedCommandBuilder;\n");
        sb.append("import org.aesh.command.impl.internal.ProcessedOption;\n");
        sb.append("import org.aesh.command.impl.internal.ProcessedOptionBuilder;\n");
        sb.append("import org.aesh.command.impl.internal.OptionType;\n");
        sb.append("import org.aesh.command.metadata.CommandMetadataProvider;\n");
        sb.append("import org.aesh.command.parser.CommandLineParserException;\n\n");

        // Class declaration
        sb.append("/**\n");
        sb.append(" * Generated compile-time metadata provider for {@link ").append(qualifiedCommandName).append("}.\n");
        sb.append(" * Do not edit — this file is regenerated by the aesh annotation processor.\n");
        sb.append(" */\n");
        sb.append("@SuppressWarnings({\"unchecked\", \"rawtypes\"})\n");
        sb.append("public final class ").append(metadataClassName);
        sb.append(" implements CommandMetadataProvider<").append(simpleName).append("> {\n\n");

        generatePrivateFieldConstants(sb, simpleName, qualifiedCommandName, fields);
        generateSharedConvertersAndCompleters(sb, fields, elementUtils, typeUtils);

        // commandType()
        sb.append("    @Override\n");
        sb.append("    public Class<").append(simpleName).append("> commandType() {\n");
        sb.append("        return ").append(simpleName).append(".class;\n");
        sb.append("    }\n\n");

        // newInstance()
        sb.append("    @Override\n");
        sb.append("    public ").append(simpleName).append(" newInstance() {\n");
        sb.append("        return new ").append(simpleName).append("();\n");
        sb.append("    }\n\n");

        // isGroupCommand()
        sb.append("    @Override\n");
        sb.append("    public boolean isGroupCommand() {\n");
        sb.append("        return ").append(isGroup).append(";\n");
        sb.append("    }\n\n");

        // groupCommandClasses()
        sb.append("    @Override\n");
        sb.append("    public Class<? extends Command>[] groupCommandClasses() {\n");
        if (isGroup) {
            generateGroupCommandClasses(sb, commandElement, elementUtils);
        } else {
            sb.append("        return new Class[0];\n");
        }
        sb.append("    }\n\n");

        // commandName() — read name via annotation mirror to avoid MirroredTypesException
        // (which can occur when @CommandDefinition has Class[] attributes like groupCommands)
        String cmdName = getAnnotationValue(commandElement, "name", elementUtils);
        sb.append("    @Override\n");
        sb.append("    public String commandName() {\n");
        sb.append("        return ").append(stringLiteral(cmdName)).append(";\n");
        sb.append("    }\n\n");

        // Collect field accessor info for the switch-based Accessor class
        List<FieldAccessorInfo> accessorInfos = new java.util.ArrayList<>();

        // Find @ParentCommand field for the Accessor class
        FieldAccessorInfo parentInfo = null;
        for (VariableElement field : fields) {
            if (field.getAnnotation(ParentCommand.class) != null) {
                parentInfo = new FieldAccessorInfo(-1, field.getSimpleName().toString(),
                        field.asType().toString(), null, isPrivateField(field), simpleName);
                break;
            }
        }

        // buildProcessedCommand()
        sb.append("    @Override\n");
        sb.append("    public ProcessedCommand buildProcessedCommand(").append(simpleName).append(" instance)");
        sb.append(" throws CommandLineParserException {\n");
        generateBuildProcessedCommand(sb, simpleName, commandElement,
                fields, isGroup, elementUtils, typeUtils, accessorInfos);
        sb.append("    }\n\n");

        // Generate the single Accessor inner class
        generateAccessorClass(sb, simpleName, accessorInfos, parentInfo);

        // End class
        sb.append("}\n");

        return sb.toString();
    }

    private static void generateGroupCommandClasses(StringBuilder sb, TypeElement commandElement, Elements elementUtils) {
        // We need to extract groupCommands() from @GroupCommandDefinition via annotation mirror
        // because accessing it directly would trigger MirroredTypesException at compile time.
        List<String> groupClasses = getGroupCommandClassNames(commandElement, elementUtils);
        if (groupClasses.isEmpty()) {
            sb.append("        return new Class[0];\n");
        } else {
            sb.append("        return new Class[] {\n");
            for (int i = 0; i < groupClasses.size(); i++) {
                sb.append("            ").append(groupClasses.get(i)).append(".class");
                if (i < groupClasses.size() - 1)
                    sb.append(",");
                sb.append("\n");
            }
            sb.append("        };\n");
        }
    }

    @SuppressWarnings("unchecked")
    private static List<String> getGroupCommandClassNames(TypeElement element, Elements elementUtils) {
        List<String> classNames = new java.util.ArrayList<>();
        for (AnnotationMirror mirror : element.getAnnotationMirrors()) {
            String annotationType = ((TypeElement) mirror.getAnnotationType().asElement())
                    .getQualifiedName().toString();
            if (annotationType.equals(GroupCommandDefinition.class.getCanonicalName())
                    || annotationType.equals(CommandDefinition.class.getCanonicalName())) {
                for (java.util.Map.Entry<? extends ExecutableElement, ? extends AnnotationValue> entry : mirror
                        .getElementValues().entrySet()) {
                    if (entry.getKey().getSimpleName().toString().equals("groupCommands")) {
                        List<? extends AnnotationValue> values = (List<? extends AnnotationValue>) entry.getValue().getValue();
                        for (AnnotationValue av : values) {
                            TypeMirror tm = (TypeMirror) av.getValue();
                            classNames.add(tm.toString());
                        }
                    }
                }
            }
        }
        return classNames;
    }

    private static class FieldAccessorInfo {
        final int index;
        final String fieldName;
        final String fieldType;
        final String mixinFieldName;
        final boolean isPrivate;
        final String commandSimpleName;
        /** True for synthetic fields (help/version) that store state in the Accessor itself. */
        final boolean synthetic;

        FieldAccessorInfo(int index, String fieldName, String fieldType, String mixinFieldName,
                boolean isPrivate, String commandSimpleName) {
            this(index, fieldName, fieldType, mixinFieldName, isPrivate, commandSimpleName, false);
        }

        FieldAccessorInfo(int index, String fieldName, String fieldType, String mixinFieldName,
                boolean isPrivate, String commandSimpleName, boolean synthetic) {
            this.index = index;
            this.fieldName = fieldName;
            this.fieldType = fieldType;
            this.mixinFieldName = mixinFieldName;
            this.isPrivate = isPrivate;
            this.commandSimpleName = commandSimpleName;
            this.synthetic = synthetic;
        }
    }

    private static void generateBuildProcessedCommand(StringBuilder sb, String simpleName,
            TypeElement commandElement,
            List<VariableElement> fields, boolean isGroup,
            Elements elementUtils, Types typeUtils,
            List<FieldAccessorInfo> accessorInfos) {

        sb.append(
                "        ProcessedCommand processedCommand = ((ProcessedCommandBuilder) ProcessedCommandBuilder.builder())\n");

        boolean generateHelp;
        String version;
        // Read all annotation values via annotation mirrors to avoid MirroredTypesException
        // (which occurs when annotations have Class[] attributes like groupCommands)
        // Determine annotation type via mirrors (safe from MirroredTypesException)
        String annotationName = hasAnnotationType(commandElement, CommandDefinition.class.getCanonicalName())
                ? CommandDefinition.class.getCanonicalName()
                : GroupCommandDefinition.class.getCanonicalName();
        generateHelp = "true".equals(getAnnotationValue(commandElement, "generateHelp", elementUtils));
        version = getAnnotationValue(commandElement, "version", elementUtils);
        if (version == null)
            version = "";

        sb.append("                .name(").append(stringLiteral(
                getAnnotationValue(commandElement, "name", elementUtils))).append(")\n");
        generateCommandActivator(sb, commandElement, isGroup, elementUtils);
        String[] aliases = getAnnotationStringArrayValue(commandElement, "aliases", elementUtils);
        sb.append("                .aliases(Arrays.asList(").append(stringArrayLiteral(aliases)).append("))\n");
        sb.append("                .description(").append(stringLiteral(
                getAnnotationValue(commandElement, "description", elementUtils))).append(")\n");
        generateCommandValidator(sb, commandElement, isGroup, elementUtils);
        sb.append("                .command(instance)\n");
        generateResultHandler(sb, commandElement, isGroup, elementUtils);
        sb.append("                .generateHelp(false)\n");
        boolean disableParsing = !isGroup && "true".equals(
                getAnnotationValue(commandElement, "disableParsing", elementUtils));
        sb.append("                .disableParsing(").append(disableParsing).append(")\n");
        sb.append("                .stopAtFirstPositional(").append(
                "true".equals(getAnnotationValue(commandElement, "stopAtFirstPositional", elementUtils)))
                .append(")\n");
        sb.append("                .sortOptions(").append(
                "true".equals(getAnnotationValue(commandElement, "sortOptions", elementUtils)))
                .append(")\n");
        generateDefaultValueProvider(sb, commandElement, isGroup, elementUtils);
        sb.append("                .version(\"\")\n");
        String helpUrl = getAnnotationValue(commandElement, "helpUrl", elementUtils);
        sb.append("                .helpUrl(").append(stringLiteral(helpUrl != null ? helpUrl : "")).append(")\n");

        sb.append("                .create();\n\n");

        // Set command-level helpGroup if present
        String cmdHelpGroup = getAnnotationValue(commandElement, "helpGroup", elementUtils);
        if (cmdHelpGroup != null && !cmdHelpGroup.isEmpty()) {
            sb.append("        processedCommand.setHelpGroup(")
                    .append(stringLiteral(cmdHelpGroup)).append(");\n\n");
        }

        // Set helpSectionProvider if not NullHelpSectionProvider
        String providerClass = getAnnotationClassValue(commandElement, annotationName,
                "helpSectionProvider", elementUtils);
        if (providerClass != null && !providerClass.equals(NULL_HELP_SECTION_PROVIDER)) {
            sb.append("        processedCommand.setHelpSectionProvider(new ")
                    .append(providerClass).append("());\n\n");
        }

        // Generate help/version options first to match reflection path declaration order
        // (reflection: constructor calls doGenerateHelp/doGenerateVersion before processCommand adds user options)
        if (generateHelp) {
            int helpIdx = accessorInfos.size();
            accessorInfos.add(new FieldAccessorInfo(helpIdx, "generatedHelp", "boolean",
                    null, false, simpleName, true));
            sb.append("        {\n");
            sb.append("            ProcessedOption helpOpt = ProcessedOption.createDirect(\n");
            sb.append("                    \"h\", \"help\", \"Display this help and exit\",\n");
            sb.append("                    Boolean.class, \"generatedHelp\", OptionType.BOOLEAN,\n");
            sb.append("                    CONVERTER_java_lang_Boolean, new Accessor(").append(helpIdx).append("));\n");
            sb.append("            helpOpt.setOverrideRequired(true);\n");
            sb.append("            processedCommand.addOptionDirect(helpOpt);\n");
            sb.append("        }\n");
            // Restore the generateHelp flag so Executions.execute() can check it
            sb.append("        processedCommand.setGenerateHelp(true);\n\n");
        }
        if (version != null && !version.isEmpty()) {
            int versionIdx = accessorInfos.size();
            accessorInfos.add(new FieldAccessorInfo(versionIdx, "generatedVersion", "boolean",
                    null, false, simpleName, true));
            sb.append("        {\n");
            sb.append("            ProcessedOption versionOpt = ProcessedOption.createDirect(\n");
            sb.append("                    \"v\", \"version\", \"Displays version information of the command\",\n");
            sb.append("                    Boolean.class, \"generatedVersion\", OptionType.BOOLEAN,\n");
            sb.append("                    CONVERTER_java_lang_Boolean, new Accessor(").append(versionIdx).append("));\n");
            sb.append("            versionOpt.setOverrideRequired(true);\n");
            sb.append("            processedCommand.addOptionDirect(versionOpt);\n");
            sb.append("        }\n");
            // Restore the version string so Executions.execute() can use it
            sb.append("        processedCommand.setVersion(").append(stringLiteral(version)).append(");\n\n");
        }

        // Process user fields
        for (VariableElement field : fields) {
            generateFieldProcessing(sb, simpleName, field, elementUtils, typeUtils, accessorInfos);
        }

        generateParentCommandInjector(sb, simpleName, fields);

        sb.append("        return processedCommand;\n");
    }

    private static void generateCommandValidator(StringBuilder sb, TypeElement element, boolean isGroup,
            Elements elementUtils) {
        String validatorClass = getAnnotationClassValue(element,
                isGroup ? GroupCommandDefinition.class.getCanonicalName() : CommandDefinition.class.getCanonicalName(),
                "validator", elementUtils);
        if (validatorClass != null && !validatorClass.equals(NULL_COMMAND_VALIDATOR)) {
            sb.append("                .validator(new ").append(validatorClass).append("())\n");
        }
    }

    private static void generateResultHandler(StringBuilder sb, TypeElement element, boolean isGroup,
            Elements elementUtils) {
        String handlerClass = getAnnotationClassValue(element,
                isGroup ? GroupCommandDefinition.class.getCanonicalName() : CommandDefinition.class.getCanonicalName(),
                "resultHandler", elementUtils);
        if (handlerClass != null && !handlerClass.equals(NULL_RESULT_HANDLER)) {
            sb.append("                .resultHandler(new ").append(handlerClass).append("())\n");
        }
    }

    private static void generateDefaultValueProvider(StringBuilder sb, TypeElement element, boolean isGroup,
            Elements elementUtils) {
        String providerClass = getAnnotationClassValue(element,
                isGroup ? GroupCommandDefinition.class.getCanonicalName() : CommandDefinition.class.getCanonicalName(),
                "defaultValueProvider", elementUtils);
        if (providerClass != null && !providerClass.equals(NULL_DEFAULT_VALUE_PROVIDER)) {
            sb.append("                .defaultValueProvider(new ").append(providerClass).append("())\n");
        }
    }

    private static void generateCommandActivator(StringBuilder sb, TypeElement element, boolean isGroup,
            Elements elementUtils) {
        String activatorClass = getAnnotationClassValue(element,
                isGroup ? GroupCommandDefinition.class.getCanonicalName() : CommandDefinition.class.getCanonicalName(),
                "activator", elementUtils);
        if (activatorClass != null && !activatorClass.equals(NULL_COMMAND_ACTIVATOR)) {
            sb.append("                .activator(new ").append(activatorClass).append("())\n");
        }
    }

    private static void generateFieldProcessing(StringBuilder sb, String simpleName, VariableElement field,
            Elements elementUtils, Types typeUtils, List<FieldAccessorInfo> accessorInfos) {
        generateFieldProcessing(sb, simpleName, field, null, elementUtils, typeUtils, accessorInfos);
    }

    private static void generateFieldProcessing(StringBuilder sb, String simpleName, VariableElement field,
            String mixinFieldName, Elements elementUtils, Types typeUtils, List<FieldAccessorInfo> accessorInfos) {
        Option o = field.getAnnotation(Option.class);
        OptionList ol = field.getAnnotation(OptionList.class);
        OptionGroup og = field.getAnnotation(OptionGroup.class);
        Arguments args = field.getAnnotation(Arguments.class);
        Argument arg = field.getAnnotation(Argument.class);

        if (o != null) {
            generateOption(sb, simpleName, field, o, mixinFieldName, elementUtils, typeUtils, accessorInfos);
        } else if (ol != null) {
            generateOptionList(sb, simpleName, field, ol, mixinFieldName, elementUtils, typeUtils, accessorInfos);
        } else if (og != null) {
            generateOptionGroup(sb, simpleName, field, og, mixinFieldName, elementUtils, typeUtils, accessorInfos);
        } else if (args != null) {
            generateArguments(sb, simpleName, field, args, mixinFieldName, elementUtils, typeUtils, accessorInfos);
        } else if (arg != null) {
            generateArgument(sb, simpleName, field, arg, mixinFieldName, elementUtils, typeUtils, accessorInfos);
        } else if (field.getAnnotation(Mixin.class) != null) {
            // Chain mixinFieldName for nested mixins: "outer" + "inner" -> "outer.inner"
            String nestedMixinName = mixinFieldName != null
                    ? mixinFieldName + "." + field.getSimpleName().toString()
                    : field.getSimpleName().toString();
            generateMixin(sb, simpleName, field, nestedMixinName, elementUtils, typeUtils, accessorInfos);
        }
    }

    private static void generateMixin(StringBuilder sb, String simpleName, VariableElement mixinField,
            String mixinFieldName, Elements elementUtils, Types typeUtils, List<FieldAccessorInfo> accessorInfos) {
        TypeMirror mixinType = mixinField.asType();
        if (!(mixinType instanceof DeclaredType))
            return;
        TypeElement mixinElement = (TypeElement) ((DeclaredType) mixinType).asElement();
        String mixinTypeName = mixinType.toString();

        if (isPrivateField(mixinField)) {
            String constName = fieldConstantName(mixinFieldName);
            sb.append("        try {\n");
            sb.append("            if (").append(constName).append(".get(instance) == null) {\n");
            sb.append("                ").append(constName).append(".set(instance, new ").append(mixinTypeName)
                    .append("());\n");
            sb.append("            }\n");
            sb.append("        } catch (IllegalAccessException e) { throw new RuntimeException(e); }\n\n");
        } else {
            sb.append("        if (instance.").append(mixinFieldName).append(" == null) {\n");
            sb.append("            instance.").append(mixinFieldName).append(" = new ").append(mixinTypeName)
                    .append("();\n");
            sb.append("        }\n\n");
        }

        generateMixinFields(sb, simpleName, mixinFieldName, mixinElement, elementUtils, typeUtils, accessorInfos);
    }

    private static void generateMixinFields(StringBuilder sb, String simpleName, String mixinFieldName,
            TypeElement typeElement, Elements elementUtils, Types typeUtils, List<FieldAccessorInfo> accessorInfos) {
        for (javax.lang.model.element.Element enclosed : typeElement.getEnclosedElements()) {
            if (enclosed instanceof VariableElement) {
                generateFieldProcessing(sb, simpleName, (VariableElement) enclosed, mixinFieldName,
                        elementUtils, typeUtils, accessorInfos);
            }
        }
        // Recurse into superclass
        TypeMirror superclass = typeElement.getSuperclass();
        if (superclass.getKind() != TypeKind.NONE && !superclass.toString().equals("java.lang.Object")) {
            if (superclass instanceof DeclaredType) {
                TypeElement superElement = (TypeElement) ((DeclaredType) superclass).asElement();
                generateMixinFields(sb, simpleName, mixinFieldName, superElement, elementUtils, typeUtils, accessorInfos);
            }
        }
    }

    private static void generateOption(StringBuilder sb, String simpleName, VariableElement field, Option o,
            String mixinFieldName, Elements elementUtils, Types typeUtils, List<FieldAccessorInfo> accessorInfos) {
        String fieldName = field.getSimpleName().toString();
        TypeMirror effectiveType = field.asType();
        boolean isOptionalWrapped = isOptionalType(effectiveType);
        if (isOptionalWrapped) {
            effectiveType = unwrapOptionalTypeMirror(effectiveType);
        }
        String fieldType = getBoxedTypeName(effectiveType, typeUtils);
        boolean isBooleanType = isBooleanType(effectiveType, typeUtils);
        String optionName = o.name().length() < 1 ? fieldName : o.name();
        String optionType = o.hasValue() ? "OptionType.NORMAL" : "OptionType.BOOLEAN";

        // Accessor index
        int accIdx = accessorInfos.size();
        accessorInfos.add(new FieldAccessorInfo(accIdx, fieldName, field.asType().toString(),
                mixinFieldName, isPrivateField(field), simpleName));

        // Emit: ProcessedOption opt_N = ProcessedOption.createDirect(...)
        String var = "opt_" + accIdx;
        sb.append("        {\n");
        sb.append("            ProcessedOption ").append(var).append(" = ProcessedOption.createDirect(\n");
        sb.append("                    ")
                .append(o.shortName() != '\u0000' ? stringLiteral(String.valueOf(o.shortName())) : "null")
                .append(", ").append(stringLiteral(optionName))
                .append(", ").append(stringLiteral(o.description())).append(",\n");
        sb.append("                    ").append(fieldType).append(".class, ")
                .append(stringLiteral(fieldName)).append(", ").append(optionType).append(",\n");
        sb.append("                    ");
        emitConverterExpression(sb, field, "converter", elementUtils, fieldType);
        sb.append(", new Accessor(").append(accIdx).append("));\n");
        // Non-default setters
        if (isOptionalWrapped)
            sb.append("            ").append(var).append(".setOptionalWrapped(true);\n");
        if (o.required())
            sb.append("            ").append(var).append(".setRequired(true);\n");
        if (o.askIfNotSet())
            sb.append("            ").append(var).append(".setAskIfNotSet(true);\n");
        if (o.acceptNameWithoutDashes())
            sb.append("            ").append(var).append(".setAcceptNameWithoutDashes(true);\n");
        if (o.defaultValue().length > 0)
            sb.append("            ").append(var).append(".setDefaultValues(java.util.Arrays.asList(")
                    .append(stringArrayLiteral(o.defaultValue())).append("));\n");
        emitCompleterSetter(sb, var, field, "completer", isBooleanType, isFileOrResourceType(effectiveType, typeUtils),
                elementUtils);
        emitCallbackSetter(sb, var, "setValidator", field, "validator", NULL_VALIDATOR, elementUtils);
        emitCallbackSetter(sb, var, "setActivator", field, "activator", NULL_ACTIVATOR, elementUtils);
        emitCallbackSetter(sb, var, "setRenderer", field, "renderer", NULL_OPTION_RENDERER, elementUtils);
        emitParserSetter(sb, var, field, "parser", elementUtils);
        if (o.overrideRequired())
            sb.append("            ").append(var).append(".setOverrideRequired(true);\n");
        if (o.optionalValue())
            sb.append("            ").append(var).append(".setOptionalValue(true);\n");
        if (!"\u0000".equals(o.fallbackValue())) {
            sb.append("            ").append(var).append(".setFallbackValue(").append(stringLiteral(o.fallbackValue()))
                    .append(");\n");
            // fallbackValue implies optionalValue
            if (!o.optionalValue())
                sb.append("            ").append(var).append(".setOptionalValue(true);\n");
        }
        if (o.negatable())
            sb.append("            ").append(var).append(".setNegatable(true);\n");
        if (!o.negationPrefix().equals("no-"))
            sb.append("            ").append(var).append(".setNegationPrefix(").append(stringLiteral(o.negationPrefix()))
                    .append(");\n");
        if (o.inherited())
            sb.append("            ").append(var).append(".setInherited(true);\n");
        if (!o.descriptionUrl().isEmpty())
            sb.append("            ").append(var).append(".setDescriptionUrl(").append(stringLiteral(o.descriptionUrl()))
                    .append(");\n");
        if (o.url())
            sb.append("            ").append(var).append(".setIsUrl(true);\n");
        emitAliasesSetter(sb, var, o.aliases());
        emitHelpGroupSetter(sb, var, o.helpGroup());
        emitExclusiveWithSetter(sb, var, o.exclusiveWith());
        emitAllowedValuesSetter(sb, var, o.allowedValues());
        emitVisibilitySetter(sb, var, o.visibility());
        if (o.order() != Integer.MAX_VALUE)
            sb.append("            ").append(var).append(".setOrder(").append(o.order()).append(");\n");
        if (mixinFieldName != null)
            sb.append("            ").append(var).append(".setMixinFieldName(").append(stringLiteral(mixinFieldName))
                    .append(");\n");
        sb.append("            processedCommand.addOptionDirect(").append(var).append(");\n");
        sb.append("        }\n\n");
    }

    private static void generateOptionList(StringBuilder sb, String simpleName, VariableElement field, OptionList ol,
            String mixinFieldName, Elements elementUtils, Types typeUtils, List<FieldAccessorInfo> accessorInfos) {
        String fieldName = field.getSimpleName().toString();
        TypeMirror effectiveType = field.asType();
        boolean isOptionalWrapped = isOptionalType(effectiveType);
        if (isOptionalWrapped) {
            effectiveType = unwrapOptionalTypeMirror(effectiveType);
        }
        String elementType = getGenericTypeArgument(effectiveType, 0, typeUtils);
        String optionName = ol.name().length() < 1 ? fieldName : ol.name();

        int accIdx = accessorInfos.size();
        accessorInfos.add(new FieldAccessorInfo(accIdx, fieldName, field.asType().toString(),
                mixinFieldName, isPrivateField(field), simpleName));

        String var = "opt_" + accIdx;
        sb.append("        {\n");
        sb.append("            ProcessedOption ").append(var).append(" = ProcessedOption.createDirect(\n");
        sb.append("                    ")
                .append(ol.shortName() != '\u0000' ? stringLiteral(String.valueOf(ol.shortName())) : "null")
                .append(", ").append(stringLiteral(optionName))
                .append(", ").append(stringLiteral(ol.description())).append(",\n");
        sb.append("                    ").append(elementType).append(".class, ")
                .append(stringLiteral(fieldName)).append(", OptionType.LIST,\n");
        sb.append("                    ");
        emitConverterExpression(sb, field, "converter", elementUtils, elementType);
        sb.append(", new Accessor(").append(accIdx).append("));\n");
        sb.append("            ").append(var).append(".setValueSeparator(").append(charLiteral(ol.valueSeparator()))
                .append(");\n");
        if (isOptionalWrapped)
            sb.append("            ").append(var).append(".setOptionalWrapped(true);\n");
        if (ol.required())
            sb.append("            ").append(var).append(".setRequired(true);\n");
        if (ol.askIfNotSet())
            sb.append("            ").append(var).append(".setAskIfNotSet(true);\n");
        if (ol.defaultValue().length > 0)
            sb.append("            ").append(var).append(".setDefaultValues(java.util.Arrays.asList(")
                    .append(stringArrayLiteral(ol.defaultValue())).append("));\n");
        emitCompleterSetter(sb, var, field, "completer", false, false, elementUtils);
        emitCallbackSetter(sb, var, "setValidator", field, "validator", NULL_VALIDATOR, elementUtils);
        emitCallbackSetter(sb, var, "setActivator", field, "activator", NULL_ACTIVATOR, elementUtils);
        emitCallbackSetter(sb, var, "setRenderer", field, "renderer", NULL_OPTION_RENDERER, elementUtils);
        emitParserSetter(sb, var, field, "parser", elementUtils);
        emitAliasesSetter(sb, var, ol.aliases());
        emitHelpGroupSetter(sb, var, ol.helpGroup());
        emitExclusiveWithSetter(sb, var, ol.exclusiveWith());
        emitAllowedValuesSetter(sb, var, ol.allowedValues());
        emitVisibilitySetter(sb, var, ol.visibility());
        if (ol.order() != Integer.MAX_VALUE)
            sb.append("            ").append(var).append(".setOrder(").append(ol.order()).append(");\n");
        if (mixinFieldName != null)
            sb.append("            ").append(var).append(".setMixinFieldName(").append(stringLiteral(mixinFieldName))
                    .append(");\n");
        sb.append("            processedCommand.addOptionDirect(").append(var).append(");\n");
        sb.append("        }\n\n");
    }

    private static void generateOptionGroup(StringBuilder sb, String simpleName, VariableElement field, OptionGroup og,
            String mixinFieldName, Elements elementUtils, Types typeUtils, List<FieldAccessorInfo> accessorInfos) {
        String fieldName = field.getSimpleName().toString();
        TypeMirror effectiveType = field.asType();
        boolean isOptionalWrapped = isOptionalType(effectiveType);
        if (isOptionalWrapped) {
            effectiveType = unwrapOptionalTypeMirror(effectiveType);
        }
        String valueType = getGenericTypeArgument(effectiveType, 1, typeUtils);
        String optionName = og.name().length() < 1
                ? (og.shortName() != '\u0000' ? "" : fieldName)
                : og.name();

        int accIdx = accessorInfos.size();
        accessorInfos.add(new FieldAccessorInfo(accIdx, fieldName, field.asType().toString(),
                mixinFieldName, isPrivateField(field), simpleName));

        String var = "opt_" + accIdx;
        sb.append("        {\n");
        sb.append("            ProcessedOption ").append(var).append(" = ProcessedOption.createDirect(\n");
        sb.append("                    ")
                .append(og.shortName() != '\u0000' ? stringLiteral(String.valueOf(og.shortName())) : "null")
                .append(", ").append(stringLiteral(optionName))
                .append(", ").append(stringLiteral(og.description())).append(",\n");
        sb.append("                    ").append(valueType).append(".class, ")
                .append(stringLiteral(fieldName)).append(", OptionType.GROUP,\n");
        sb.append("                    ");
        emitConverterExpression(sb, field, "converter", elementUtils, valueType);
        sb.append(", new Accessor(").append(accIdx).append("));\n");
        sb.append("            ").append(var).append(".setValueSeparator(',');\n");
        if (isOptionalWrapped)
            sb.append("            ").append(var).append(".setOptionalWrapped(true);\n");
        if (og.required())
            sb.append("            ").append(var).append(".setRequired(true);\n");
        if (og.askIfNotSet())
            sb.append("            ").append(var).append(".setAskIfNotSet(true);\n");
        if (og.defaultValue().length > 0)
            sb.append("            ").append(var).append(".setDefaultValues(java.util.Arrays.asList(")
                    .append(stringArrayLiteral(og.defaultValue())).append("));\n");
        emitCompleterSetter(sb, var, field, "completer", false, false, elementUtils);
        emitCallbackSetter(sb, var, "setValidator", field, "validator", NULL_VALIDATOR, elementUtils);
        emitCallbackSetter(sb, var, "setActivator", field, "activator", NULL_ACTIVATOR, elementUtils);
        emitCallbackSetter(sb, var, "setRenderer", field, "renderer", NULL_OPTION_RENDERER, elementUtils);
        emitParserSetter(sb, var, field, "parser", elementUtils);
        emitVisibilitySetter(sb, var, og.visibility());
        if (og.order() != Integer.MAX_VALUE)
            sb.append("            ").append(var).append(".setOrder(").append(og.order()).append(");\n");
        if (mixinFieldName != null)
            sb.append("            ").append(var).append(".setMixinFieldName(").append(stringLiteral(mixinFieldName))
                    .append(");\n");
        sb.append("            processedCommand.addOptionDirect(").append(var).append(");\n");
        sb.append("        }\n\n");
    }

    private static void generateArguments(StringBuilder sb, String simpleName, VariableElement field, Arguments a,
            String mixinFieldName, Elements elementUtils, Types typeUtils, List<FieldAccessorInfo> accessorInfos) {
        String fieldName = field.getSimpleName().toString();
        TypeMirror effectiveType = field.asType();
        boolean isOptionalWrapped = isOptionalType(effectiveType);
        if (isOptionalWrapped) {
            effectiveType = unwrapOptionalTypeMirror(effectiveType);
        }
        String elementType = getGenericTypeArgument(effectiveType, 0, typeUtils);

        int accIdx = accessorInfos.size();
        accessorInfos.add(new FieldAccessorInfo(accIdx, fieldName, field.asType().toString(),
                mixinFieldName, isPrivateField(field), simpleName));

        String var = "argsOpt_" + accIdx;
        sb.append("        {\n");
        sb.append("            ProcessedOption ").append(var).append(" = ProcessedOption.createDirect(\n");
        sb.append("                    null, \"\", ").append(stringLiteral(a.description())).append(",\n");
        sb.append("                    ").append(elementType).append(".class, ")
                .append(stringLiteral(fieldName)).append(", OptionType.ARGUMENTS,\n");
        sb.append("                    ");
        emitConverterExpression(sb, field, "converter", elementUtils, elementType);
        sb.append(", new Accessor(").append(accIdx).append("));\n");
        if (isOptionalWrapped)
            sb.append("            ").append(var).append(".setOptionalWrapped(true);\n");
        if (a.required())
            sb.append("            ").append(var).append(".setRequired(true);\n");
        if (a.valueSeparator() != ' ')
            sb.append("            ").append(var).append(".setValueSeparator(").append(charLiteral(a.valueSeparator()))
                    .append(");\n");
        if (a.selector() != org.aesh.selector.SelectorType.NO_OP)
            sb.append("            ").append(var).append(".setSelectorType(").append(selectorLiteral(a.selector()))
                    .append(");\n");
        if (a.askIfNotSet())
            sb.append("            ").append(var).append(".setAskIfNotSet(true);\n");
        if (a.defaultValue().length > 0)
            sb.append("            ").append(var).append(".setDefaultValues(java.util.Arrays.asList(")
                    .append(stringArrayLiteral(a.defaultValue())).append("));\n");
        if (!a.paramLabel().isEmpty())
            sb.append("            ").append(var).append(".setParamLabel(").append(stringLiteral(a.paramLabel()))
                    .append(");\n");
        if (!a.arity().isEmpty())
            sb.append("            ").append(var).append(".setArity(").append(stringLiteral(a.arity())).append(");\n");
        sb.append("            ").append(var).append(".setIndex(").append(stringLiteral(a.index())).append(");\n");
        emitCompleterSetter(sb, var, field, "completer", false, false, elementUtils);
        emitCallbackSetter(sb, var, "setValidator", field, "validator", NULL_VALIDATOR, elementUtils);
        emitCallbackSetter(sb, var, "setActivator", field, "activator", NULL_ACTIVATOR, elementUtils);
        emitParserSetter(sb, var, field, "parser", elementUtils);
        if (a.url())
            sb.append("            ").append(var).append(".setIsUrl(true);\n");
        if (mixinFieldName != null)
            sb.append("            ").append(var).append(".setMixinFieldName(").append(stringLiteral(mixinFieldName))
                    .append(");\n");
        sb.append("            processedCommand.setArguments(").append(var).append(");\n");
        sb.append("        }\n\n");
    }

    private static void generateArgument(StringBuilder sb, String simpleName, VariableElement field, Argument arg,
            String mixinFieldName, Elements elementUtils, Types typeUtils, List<FieldAccessorInfo> accessorInfos) {
        String fieldName = field.getSimpleName().toString();
        TypeMirror effectiveType = field.asType();
        boolean isOptionalWrapped = isOptionalType(effectiveType);
        if (isOptionalWrapped) {
            effectiveType = unwrapOptionalTypeMirror(effectiveType);
        }
        String fieldType = getBoxedTypeName(effectiveType, typeUtils);

        int accIdx = accessorInfos.size();
        accessorInfos.add(new FieldAccessorInfo(accIdx, fieldName, field.asType().toString(),
                mixinFieldName, isPrivateField(field), simpleName));

        String var = "argOpt_" + accIdx;
        sb.append("        {\n");
        sb.append("            ProcessedOption ").append(var).append(" = ProcessedOption.createDirect(\n");
        sb.append("                    null, \"\", ").append(stringLiteral(arg.description())).append(",\n");
        sb.append("                    ").append(fieldType).append(".class, ")
                .append(stringLiteral(fieldName)).append(", OptionType.ARGUMENT,\n");
        sb.append("                    ");
        emitConverterExpression(sb, field, "converter", elementUtils, fieldType);
        sb.append(", new Accessor(").append(accIdx).append("));\n");
        if (isOptionalWrapped)
            sb.append("            ").append(var).append(".setOptionalWrapped(true);\n");
        if (arg.required())
            sb.append("            ").append(var).append(".setRequired(true);\n");
        if (arg.askIfNotSet())
            sb.append("            ").append(var).append(".setAskIfNotSet(true);\n");
        if (arg.selector() != org.aesh.selector.SelectorType.NO_OP)
            sb.append("            ").append(var).append(".setSelectorType(").append(selectorLiteral(arg.selector()))
                    .append(");\n");
        if (arg.defaultValue().length > 0)
            sb.append("            ").append(var).append(".setDefaultValues(java.util.Arrays.asList(")
                    .append(stringArrayLiteral(arg.defaultValue())).append("));\n");
        if (!arg.paramLabel().isEmpty())
            sb.append("            ").append(var).append(".setParamLabel(").append(stringLiteral(arg.paramLabel()))
                    .append(");\n");
        if (!arg.arity().isEmpty())
            sb.append("            ").append(var).append(".setArity(").append(stringLiteral(arg.arity())).append(");\n");
        sb.append("            ").append(var).append(".setIndex(").append(stringLiteral(arg.index())).append(");\n");
        emitCompleterSetter(sb, var, field, "completer", false, isFileOrResourceType(field.asType(), typeUtils),
                elementUtils);
        emitCallbackSetter(sb, var, "setValidator", field, "validator", NULL_VALIDATOR, elementUtils);
        emitCallbackSetter(sb, var, "setActivator", field, "activator", NULL_ACTIVATOR, elementUtils);
        emitCallbackSetter(sb, var, "setRenderer", field, "renderer", NULL_OPTION_RENDERER, elementUtils);
        emitParserSetter(sb, var, field, "parser", elementUtils);
        if (arg.overrideRequired())
            sb.append("            ").append(var).append(".setOverrideRequired(true);\n");
        if (arg.inherited())
            sb.append("            ").append(var).append(".setInherited(true);\n");
        if (arg.url())
            sb.append("            ").append(var).append(".setIsUrl(true);\n");
        if (mixinFieldName != null)
            sb.append("            ").append(var).append(".setMixinFieldName(").append(stringLiteral(mixinFieldName))
                    .append(");\n");
        sb.append("            processedCommand.addArgument(").append(var).append(");\n");
        sb.append("        }\n\n");
    }

    private static void generateAccessorClass(StringBuilder sb, String commandSimpleName,
            List<FieldAccessorInfo> infos, FieldAccessorInfo parentInfo) {
        sb.append("    static final class Accessor implements org.aesh.command.impl.internal.FieldAccessor,\n");
        sb.append("            java.util.function.BiConsumer<Object, Object> {\n");

        sb.append("        static final Accessor PARENT_INJECTOR = new Accessor(-1);\n\n");

        // Synthetic fields for generated help/version options — state held in the Accessor instance
        for (FieldAccessorInfo info : infos) {
            if (info.synthetic) {
                sb.append("        private boolean ").append(info.fieldName).append(";\n");
            }
        }

        sb.append("        private final int idx;\n");
        sb.append("        Accessor(int idx) { this.idx = idx; }\n\n");

        // set method
        sb.append("        public void set(Object inst, Object val) {\n");
        sb.append("            switch (idx) {\n");
        for (FieldAccessorInfo info : infos) {
            sb.append("                case ").append(info.index).append(": ");
            if (info.synthetic) {
                sb.append("this.").append(info.fieldName)
                        .append(" = val != null && (Boolean) val;");
            } else if (info.mixinFieldName != null) {
                if (info.isPrivate) {
                    sb.append("try { Object m = ").append(fieldConstantName(info.mixinFieldName))
                            .append(".get(inst); if (m != null) ")
                            .append(fieldConstantName(info.mixinFieldName, info.fieldName))
                            .append(".set(m, val); } catch (IllegalAccessException e) { throw new RuntimeException(e); }");
                } else {
                    sb.append("if (((").append(info.commandSimpleName).append(") inst).")
                            .append(info.mixinFieldName).append(" != null) ((")
                            .append(info.commandSimpleName).append(") inst).")
                            .append(info.mixinFieldName).append(".").append(info.fieldName)
                            .append(" = (").append(info.fieldType).append(") val;");
                }
            } else {
                if (info.isPrivate) {
                    sb.append("try { ").append(fieldConstantName(info.fieldName))
                            .append(".set(inst, val); } catch (IllegalAccessException e) { throw new RuntimeException(e); }");
                } else {
                    sb.append("((").append(info.commandSimpleName).append(") inst).")
                            .append(info.fieldName).append(" = (").append(info.fieldType).append(") val;");
                }
            }
            sb.append(" break;\n");
        }
        sb.append("            }\n");
        sb.append("        }\n\n");

        // get method
        sb.append("        public Object get(Object inst) {\n");
        sb.append("            switch (idx) {\n");
        for (FieldAccessorInfo info : infos) {
            sb.append("                case ").append(info.index).append(": ");
            if (info.synthetic) {
                sb.append("return this.").append(info.fieldName).append(";");
            } else if (info.mixinFieldName != null) {
                if (info.isPrivate) {
                    sb.append("try { Object m = ").append(fieldConstantName(info.mixinFieldName))
                            .append(".get(inst); return m != null ? ")
                            .append(fieldConstantName(info.mixinFieldName, info.fieldName))
                            .append(".get(m) : null; } catch (IllegalAccessException e) { throw new RuntimeException(e); }");
                } else {
                    sb.append("return ((").append(info.commandSimpleName).append(") inst).")
                            .append(info.mixinFieldName).append(" != null ? ((")
                            .append(info.commandSimpleName).append(") inst).")
                            .append(info.mixinFieldName).append(".").append(info.fieldName).append(" : null;");
                }
            } else {
                if (info.isPrivate) {
                    sb.append("try { return ").append(fieldConstantName(info.fieldName))
                            .append(".get(inst); } catch (IllegalAccessException e) { throw new RuntimeException(e); }");
                } else {
                    sb.append("return ((").append(info.commandSimpleName).append(") inst).")
                            .append(info.fieldName).append(";");
                }
            }
            sb.append("\n");
        }
        sb.append("                default: return null;\n");
        sb.append("            }\n");
        sb.append("        }\n\n");

        // accept method (BiConsumer for parent command injection)
        sb.append("        @Override\n");
        sb.append("        public void accept(Object cmd, Object parent) {\n");
        if (parentInfo != null) {
            if (parentInfo.isPrivate) {
                sb.append("            try { ").append(fieldConstantName(parentInfo.fieldName))
                        .append(".set(cmd, parent); }\n");
                sb.append("            catch (IllegalAccessException e) { throw new RuntimeException(e); }\n");
            } else {
                sb.append("            ((").append(commandSimpleName).append(") cmd).").append(parentInfo.fieldName)
                        .append(" = (").append(parentInfo.fieldType).append(") parent;\n");
            }
        }
        sb.append("        }\n");
        sb.append("    }\n");
    }

    private static void generateAliases(StringBuilder sb, String[] aliases) {
        if (aliases != null && aliases.length > 0) {
            sb.append("                        .aliases(").append(stringArrayLiteralAsNew(aliases)).append(")\n");
        }
    }

    private static void generateHelpGroup(StringBuilder sb, String helpGroup) {
        if (helpGroup != null && !helpGroup.isEmpty()) {
            sb.append("                        .helpGroup(").append(stringLiteral(helpGroup)).append(")\n");
        }
    }

    private static void generateExclusiveWith(StringBuilder sb, String[] exclusiveWith) {
        if (exclusiveWith != null && exclusiveWith.length > 0) {
            sb.append("                        .exclusiveWith(").append(stringArrayLiteralAsNew(exclusiveWith)).append(")\n");
        }
    }

    private static void generateAllowedValues(StringBuilder sb, String[] allowedValues) {
        if (allowedValues != null && allowedValues.length > 0) {
            sb.append("                        .addAllAllowedValues(").append(stringArrayLiteralAsNew(allowedValues))
                    .append(")\n");
        }
    }

    private static void generateVisibility(StringBuilder sb, org.aesh.command.option.OptionVisibility visibility) {
        if (visibility != org.aesh.command.option.OptionVisibility.BRIEF) {
            sb.append("                        .visibility(org.aesh.command.option.OptionVisibility.")
                    .append(visibility.name()).append(")\n");
        }
    }

    // --- Helper methods for generating option component instantiation ---

    private static void generateOptionConverter(StringBuilder sb, VariableElement field,
            String attributeName, Elements elementUtils) {
        String className = getFieldAnnotationClassValue(field, attributeName, elementUtils);
        if (className != null && !className.equals(NULL_CONVERTER)) {
            sb.append("                        .converter(new ").append(className).append("())\n");
        }
        // When NullConverter (default), skip — build() auto-resolves from type via CLConverterManager
    }

    private static void generateOptionCompleter(StringBuilder sb, VariableElement field,
            String attributeName, boolean isBooleanType, boolean isFileOrResource, Elements elementUtils) {
        String className = getFieldAnnotationClassValue(field, attributeName, elementUtils);
        if (className != null && !className.equals(NULL_OPTION_COMPLETER)) {
            sb.append("                        .completer(new ").append(className).append("())\n");
        } else if (isBooleanType) {
            sb.append("                        .completer(new org.aesh.command.impl.completer.BooleanOptionCompleter())\n");
        } else if (isFileOrResource) {
            sb.append("                        .completer(new org.aesh.command.impl.completer.FileOptionCompleter())\n");
        }
        // When NullOptionCompleter and not boolean/file, skip — null completer is the default
    }

    private static void generateOptionValidator(StringBuilder sb, VariableElement field,
            String attributeName, Elements elementUtils) {
        String className = getFieldAnnotationClassValue(field, attributeName, elementUtils);
        if (className != null && !className.equals(NULL_VALIDATOR)) {
            sb.append("                        .validator(new ").append(className).append("())\n");
        }
    }

    private static void generateOptionActivator(StringBuilder sb, VariableElement field,
            String attributeName, Elements elementUtils) {
        String className = getFieldAnnotationClassValue(field, attributeName, elementUtils);
        if (className != null && !className.equals(NULL_ACTIVATOR)) {
            sb.append("                        .activator(new ").append(className).append("())\n");
        }
    }

    private static void generateOptionRenderer(StringBuilder sb, VariableElement field,
            String attributeName, Elements elementUtils) {
        String className = getFieldAnnotationClassValue(field, attributeName, elementUtils);
        if (className != null && !className.equals(NULL_OPTION_RENDERER)) {
            sb.append("                        .renderer(new ").append(className).append("())\n");
        }
    }

    private static void generateOptionParser(StringBuilder sb, VariableElement field,
            String attributeName, Elements elementUtils) {
        String className = getFieldAnnotationClassValue(field, attributeName, elementUtils);
        if (className != null && !className.equals(AESH_OPTION_PARSER)) {
            sb.append("                        .parser(new ").append(className).append("())\n");
        }
        // When AeshOptionParser (default), skip — ProcessedOption.parser() lazy-creates it
    }

    // --- Helper methods for createDirect() path ---

    /** Emit a converter expression inline (for createDirect() call). */
    private static void emitConverterExpression(StringBuilder sb, VariableElement field,
            String attributeName, Elements elementUtils, String fieldType) {
        String className = getFieldAnnotationClassValue(field, attributeName, elementUtils);
        if (className != null && !className.equals(NULL_CONVERTER)) {
            sb.append("new ").append(className).append("()");
        } else {
            sb.append("CONVERTER_").append(converterConstantSuffix(fieldType));
        }
    }

    /** Emit completer setter if non-default. */
    private static void emitCompleterSetter(StringBuilder sb, String var, VariableElement field,
            String attributeName, boolean isBooleanType, boolean isFileOrResource, Elements elementUtils) {
        String className = getFieldAnnotationClassValue(field, attributeName, elementUtils);
        if (className != null && !className.equals(NULL_OPTION_COMPLETER)) {
            sb.append("            ").append(var).append(".setCompleter(new ").append(className).append("());\n");
        } else if (isBooleanType) {
            sb.append("            ").append(var).append(".setCompleter(BOOLEAN_COMPLETER);\n");
        } else if (isFileOrResource) {
            sb.append("            ").append(var)
                    .append(".setCompleter(new org.aesh.command.impl.completer.FileOptionCompleter());\n");
        }
    }

    /** Emit parser setter if non-default (for createDirect() path). */
    private static void emitParserSetter(StringBuilder sb, String var, VariableElement field,
            String attributeName, Elements elementUtils) {
        String className = getFieldAnnotationClassValue(field, attributeName, elementUtils);
        if (className != null && !className.equals(AESH_OPTION_PARSER)) {
            sb.append("            ").append(var).append(".setParser(new ").append(className).append("());\n");
        }
    }

    /** Emit a generic callback setter (validator, activator, renderer). */
    private static void emitCallbackSetter(StringBuilder sb, String var, String setterName,
            VariableElement field, String attributeName, String nullSentinel, Elements elementUtils) {
        String className = getFieldAnnotationClassValue(field, attributeName, elementUtils);
        if (className != null && !className.equals(nullSentinel)) {
            sb.append("            ").append(var).append(".").append(setterName)
                    .append("(new ").append(className).append("());\n");
        }
    }

    private static void emitAliasesSetter(StringBuilder sb, String var, String[] aliases) {
        if (aliases != null && aliases.length > 0) {
            sb.append("            ").append(var).append(".setAliases(java.util.Arrays.asList(")
                    .append(stringArrayLiteral(aliases)).append("));\n");
        }
    }

    private static void emitHelpGroupSetter(StringBuilder sb, String var, String helpGroup) {
        if (helpGroup != null && !helpGroup.isEmpty()) {
            sb.append("            ").append(var).append(".setHelpGroup(").append(stringLiteral(helpGroup)).append(");\n");
        }
    }

    private static void emitExclusiveWithSetter(StringBuilder sb, String var, String[] exclusiveWith) {
        if (exclusiveWith != null && exclusiveWith.length > 0) {
            sb.append("            ").append(var).append(".setExclusiveWith(java.util.Arrays.asList(")
                    .append(stringArrayLiteral(exclusiveWith)).append("));\n");
        }
    }

    private static void emitAllowedValuesSetter(StringBuilder sb, String var, String[] allowedValues) {
        if (allowedValues != null && allowedValues.length > 0) {
            sb.append("            ").append(var).append(".setAllowedValues(java.util.Arrays.asList(")
                    .append(stringArrayLiteral(allowedValues)).append("));\n");
            // Mirror ProcessedOptionBuilder.build(): auto-create DefaultValueOptionCompleter when
            // allowedValues is non-empty and no custom completer was set
            sb.append("            if (").append(var).append(".completer() == null) ").append(var)
                    .append(".setCompleter(new org.aesh.command.impl.completer.DefaultValueOptionCompleter(")
                    .append(var).append(".getAllowedValues()));\n");
        }
    }

    private static void emitVisibilitySetter(StringBuilder sb, String var,
            org.aesh.command.option.OptionVisibility visibility) {
        if (visibility != org.aesh.command.option.OptionVisibility.BRIEF) {
            sb.append("            ").append(var).append(".setVisibility(org.aesh.command.option.OptionVisibility.")
                    .append(visibility.name()).append(");\n");
        }
    }

    private static void generateParentCommandInjector(StringBuilder sb, String simpleName,
            List<VariableElement> fields) {
        // Always set the injector — when there's no @ParentCommand field,
        // the Accessor's accept() is a no-op, which prevents the reflection
        // fallback in Executions.injectParentCommand() from scanning getDeclaredFields()
        sb.append("        processedCommand.setParentCommandInjector(Accessor.PARENT_INJECTOR);\n\n");
    }

    private static boolean isPrivateField(VariableElement field) {
        return field.getModifiers().contains(javax.lang.model.element.Modifier.PRIVATE);
    }

    private static String fieldConstantName(String fieldName) {
        return "FIELD_" + fieldName.replace('.', '_');
    }

    private static String fieldConstantName(String mixinFieldName, String fieldName) {
        return "FIELD_" + mixinFieldName.replace('.', '_') + "_" + fieldName;
    }

    private static boolean hasAnnotation(VariableElement field) {
        return field.getAnnotation(Option.class) != null
                || field.getAnnotation(OptionList.class) != null
                || field.getAnnotation(OptionGroup.class) != null
                || field.getAnnotation(Argument.class) != null
                || field.getAnnotation(Arguments.class) != null;
    }

    private static String declaringClassName(VariableElement field) {
        return ((TypeElement) field.getEnclosingElement()).getQualifiedName().toString();
    }

    private static void generatePrivateFieldConstants(StringBuilder sb, String simpleName,
            String qualifiedCommandName, List<VariableElement> fields) {
        List<String[]> privateFields = new ArrayList<>();

        for (VariableElement field : fields) {
            if (isPrivateField(field) && (hasAnnotation(field) || field.getAnnotation(ParentCommand.class) != null)) {
                privateFields.add(new String[] {
                        fieldConstantName(field.getSimpleName().toString()),
                        declaringClassName(field),
                        field.getSimpleName().toString()
                });
            }
            if (field.getAnnotation(Mixin.class) != null) {
                String mixinFieldName = field.getSimpleName().toString();
                TypeMirror mixinType = field.asType();
                if (mixinType instanceof DeclaredType) {
                    if (isPrivateField(field)) {
                        privateFields.add(new String[] {
                                fieldConstantName(mixinFieldName),
                                declaringClassName(field),
                                mixinFieldName
                        });
                    }
                    TypeElement mixinElement = (TypeElement) ((DeclaredType) mixinType).asElement();
                    collectMixinPrivateFields(privateFields, mixinFieldName, mixinElement);
                }
            }
        }

        if (privateFields.isEmpty())
            return;

        for (String[] pf : privateFields) {
            sb.append("    private static final java.lang.reflect.Field ").append(pf[0]).append(";\n");
        }
        sb.append("\n    static {\n");
        sb.append("        try {\n");
        for (String[] pf : privateFields) {
            sb.append("            ").append(pf[0]).append(" = ").append(pf[1])
                    .append(".class.getDeclaredField(\"").append(pf[2]).append("\");\n");
            sb.append("            ").append(pf[0]).append(".setAccessible(true);\n");
        }
        sb.append("        } catch (NoSuchFieldException e) {\n");
        sb.append("            throw new RuntimeException(e);\n");
        sb.append("        }\n");
        sb.append("    }\n\n");
    }

    /**
     * Pre-scan fields to find distinct converter types and completer needs,
     * then emit shared static final constants to avoid per-option allocations.
     */
    private static void generateSharedConvertersAndCompleters(StringBuilder sb,
            List<VariableElement> fields, Elements elementUtils, Types typeUtils) {
        // Collect distinct default converter types (types that use CLConverterManager, not custom converters)
        java.util.LinkedHashSet<String> converterTypes = new java.util.LinkedHashSet<>();
        // Always include Boolean — needed for generated help/version options
        converterTypes.add("java.lang.Boolean");
        boolean needsBooleanCompleter = false;

        for (VariableElement field : fields) {
            if (field.getAnnotation(Mixin.class) != null) {
                TypeMirror mixinType = field.asType();
                if (mixinType instanceof DeclaredType) {
                    TypeElement mixinElement = (TypeElement) ((DeclaredType) mixinType).asElement();
                    collectConverterTypes(converterTypes, mixinElement, elementUtils, typeUtils);
                    if (hasBooleanOptions(mixinElement, typeUtils))
                        needsBooleanCompleter = true;
                }
                continue;
            }
            String customConverter = getFieldAnnotationClassValue(field, "converter", elementUtils);
            if (customConverter != null && !customConverter.equals(NULL_CONVERTER))
                continue; // custom converter, not shared
            if (field.getAnnotation(Option.class) != null || field.getAnnotation(Argument.class) != null) {
                TypeMirror effectiveType = field.asType();
                if (isOptionalType(effectiveType))
                    effectiveType = unwrapOptionalTypeMirror(effectiveType);
                converterTypes.add(getBoxedTypeName(effectiveType, typeUtils));
                if (isBooleanType(effectiveType, typeUtils))
                    needsBooleanCompleter = true;
            } else if (field.getAnnotation(OptionList.class) != null || field.getAnnotation(Arguments.class) != null) {
                TypeMirror effectiveType = field.asType();
                if (isOptionalType(effectiveType))
                    effectiveType = unwrapOptionalTypeMirror(effectiveType);
                converterTypes.add(getGenericTypeArgument(effectiveType, 0, typeUtils));
            } else if (field.getAnnotation(OptionGroup.class) != null) {
                TypeMirror effectiveType = field.asType();
                if (isOptionalType(effectiveType))
                    effectiveType = unwrapOptionalTypeMirror(effectiveType);
                converterTypes.add(getGenericTypeArgument(effectiveType, 1, typeUtils));
            }
        }

        if (converterTypes.isEmpty() && !needsBooleanCompleter)
            return;

        // Emit converter constants
        for (String type : converterTypes) {
            sb.append("    private static final org.aesh.command.converter.Converter CONVERTER_")
                    .append(converterConstantSuffix(type))
                    .append(" = org.aesh.converter.CLConverterManager.getInstance().getConverter(")
                    .append(type).append(".class);\n");
        }
        if (needsBooleanCompleter) {
            sb.append("    private static final org.aesh.command.completer.OptionCompleter BOOLEAN_COMPLETER")
                    .append(" = new org.aesh.command.impl.completer.BooleanOptionCompleter();\n");
        }
        sb.append("\n");
    }

    /** Generate a safe Java identifier suffix from a type name. */
    private static String converterConstantSuffix(String typeName) {
        return typeName.replace('.', '_').replace('$', '_');
    }

    private static void collectConverterTypes(java.util.Set<String> types, TypeElement typeElement,
            Elements elementUtils, Types typeUtils) {
        for (javax.lang.model.element.Element enclosed : typeElement.getEnclosedElements()) {
            if (!(enclosed instanceof VariableElement))
                continue;
            VariableElement f = (VariableElement) enclosed;
            String customConverter = getFieldAnnotationClassValue(f, "converter", elementUtils);
            if (customConverter != null && !customConverter.equals(NULL_CONVERTER))
                continue;
            if (f.getAnnotation(Option.class) != null || f.getAnnotation(Argument.class) != null) {
                types.add(getBoxedTypeName(f.asType(), typeUtils));
            } else if (f.getAnnotation(OptionList.class) != null || f.getAnnotation(Arguments.class) != null) {
                types.add(getGenericTypeArgument(f.asType(), 0, typeUtils));
            } else if (f.getAnnotation(OptionGroup.class) != null) {
                types.add(getGenericTypeArgument(f.asType(), 1, typeUtils));
            }
        }
        // Recurse into superclass
        TypeMirror superclass = typeElement.getSuperclass();
        if (superclass.getKind() != TypeKind.NONE && !superclass.toString().equals("java.lang.Object")) {
            if (superclass instanceof DeclaredType) {
                collectConverterTypes(types, (TypeElement) ((DeclaredType) superclass).asElement(),
                        elementUtils, typeUtils);
            }
        }
    }

    private static boolean hasBooleanOptions(TypeElement typeElement, Types typeUtils) {
        for (javax.lang.model.element.Element enclosed : typeElement.getEnclosedElements()) {
            if (enclosed instanceof VariableElement) {
                VariableElement f = (VariableElement) enclosed;
                if ((f.getAnnotation(Option.class) != null) && isBooleanType(f.asType(), typeUtils))
                    return true;
            }
        }
        return false;
    }

    private static void collectMixinPrivateFields(List<String[]> privateFields,
            String mixinFieldName, TypeElement mixinElement) {
        String mixinClassName = mixinElement.getQualifiedName().toString();
        for (javax.lang.model.element.Element enclosed : mixinElement.getEnclosedElements()) {
            if (enclosed instanceof VariableElement) {
                VariableElement f = (VariableElement) enclosed;
                if (isPrivateField(f) && hasAnnotation(f)) {
                    privateFields.add(new String[] {
                            fieldConstantName(mixinFieldName, f.getSimpleName().toString()),
                            mixinClassName,
                            f.getSimpleName().toString()
                    });
                }
            }
        }
        TypeMirror superclass = mixinElement.getSuperclass();
        if (superclass.getKind() != TypeKind.NONE && !superclass.toString().equals("java.lang.Object")) {
            if (superclass instanceof DeclaredType) {
                collectMixinPrivateFields(privateFields, mixinFieldName,
                        (TypeElement) ((DeclaredType) superclass).asElement());
            }
        }
    }

    // --- Annotation class value extraction (handles MirroredTypeException) ---

    /**
     * Extract the Class value of a named annotation attribute from the field's
     * option annotation. Returns the fully-qualified class name, or null if not found.
     */
    private static String getFieldAnnotationClassValue(VariableElement field, String attributeName,
            Elements elementUtils) {
        // Check which annotation is on this field and extract from it
        String[] annotationTypes = {
                Option.class.getCanonicalName(),
                OptionList.class.getCanonicalName(),
                OptionGroup.class.getCanonicalName(),
                Arguments.class.getCanonicalName(),
                Argument.class.getCanonicalName()
        };

        for (AnnotationMirror mirror : field.getAnnotationMirrors()) {
            String annotationType = ((TypeElement) mirror.getAnnotationType().asElement())
                    .getQualifiedName().toString();
            for (String expected : annotationTypes) {
                if (annotationType.equals(expected)) {
                    return extractClassAttribute(mirror, attributeName);
                }
            }
        }
        return null;
    }

    private static String getAnnotationClassValue(TypeElement element, String annotationType,
            String attributeName, Elements elementUtils) {
        for (AnnotationMirror mirror : element.getAnnotationMirrors()) {
            String mirrorType = ((TypeElement) mirror.getAnnotationType().asElement())
                    .getQualifiedName().toString();
            if (mirrorType.equals(annotationType)) {
                return extractClassAttribute(mirror, attributeName);
            }
        }
        return null;
    }

    private static String extractClassAttribute(AnnotationMirror mirror, String attributeName) {
        for (java.util.Map.Entry<? extends ExecutableElement, ? extends AnnotationValue> entry : mirror.getElementValues()
                .entrySet()) {
            if (entry.getKey().getSimpleName().toString().equals(attributeName)) {
                Object value = entry.getValue().getValue();
                if (value instanceof TypeMirror) {
                    return ((TypeMirror) value).toString();
                }
            }
        }
        return null;
    }

    private static boolean hasAnnotationType(TypeElement element, String annotationType) {
        for (AnnotationMirror mirror : element.getAnnotationMirrors()) {
            String mirrorType = ((TypeElement) mirror.getAnnotationType().asElement())
                    .getQualifiedName().toString();
            if (mirrorType.equals(annotationType))
                return true;
        }
        return false;
    }

    /**
     * Read a string or boolean annotation value via annotation mirrors.
     * Safe from MirroredTypesException.
     */
    private static String getAnnotationValue(TypeElement element, String attributeName, Elements elementUtils) {
        for (AnnotationMirror mirror : element.getAnnotationMirrors()) {
            String mirrorType = ((TypeElement) mirror.getAnnotationType().asElement())
                    .getQualifiedName().toString();
            if (mirrorType.equals(CommandDefinition.class.getCanonicalName())
                    || mirrorType.equals(GroupCommandDefinition.class.getCanonicalName())) {
                for (java.util.Map.Entry<? extends ExecutableElement, ? extends AnnotationValue> entry : mirror
                        .getElementValues().entrySet()) {
                    if (entry.getKey().getSimpleName().toString().equals(attributeName)) {
                        return String.valueOf(entry.getValue().getValue());
                    }
                }
            }
        }
        return null;
    }

    /**
     * Read a String[] annotation value via annotation mirrors.
     */
    @SuppressWarnings("unchecked")
    private static String[] getAnnotationStringArrayValue(TypeElement element, String attributeName,
            Elements elementUtils) {
        for (AnnotationMirror mirror : element.getAnnotationMirrors()) {
            String mirrorType = ((TypeElement) mirror.getAnnotationType().asElement())
                    .getQualifiedName().toString();
            if (mirrorType.equals(CommandDefinition.class.getCanonicalName())
                    || mirrorType.equals(GroupCommandDefinition.class.getCanonicalName())) {
                for (java.util.Map.Entry<? extends ExecutableElement, ? extends AnnotationValue> entry : mirror
                        .getElementValues().entrySet()) {
                    if (entry.getKey().getSimpleName().toString().equals(attributeName)) {
                        List<? extends AnnotationValue> values = (List<? extends AnnotationValue>) entry.getValue().getValue();
                        String[] result = new String[values.size()];
                        for (int i = 0; i < values.size(); i++) {
                            result[i] = String.valueOf(values.get(i).getValue());
                        }
                        return result;
                    }
                }
            }
        }
        return new String[0];
    }

    // --- Type utility methods ---

    private static boolean isOptionalType(TypeMirror type) {
        return type.toString().startsWith("java.util.Optional");
    }

    /**
     * Unwrap Optional&lt;T&gt; to get T from a field's type mirror.
     */
    private static TypeMirror unwrapOptionalTypeMirror(TypeMirror type) {
        if (type instanceof DeclaredType) {
            DeclaredType declaredType = (DeclaredType) type;
            List<? extends TypeMirror> typeArgs = declaredType.getTypeArguments();
            if (!typeArgs.isEmpty()) {
                return typeArgs.get(0);
            }
        }
        return type;
    }

    private static boolean isBooleanType(TypeMirror type, Types typeUtils) {
        if (type.getKind() == TypeKind.BOOLEAN)
            return true;
        String name = type.toString();
        return name.equals("java.lang.Boolean");
    }

    private static boolean isFileOrResourceType(TypeMirror type, Types typeUtils) {
        String name = type.toString();
        return name.equals("java.io.File") || name.equals("org.aesh.io.Resource");
    }

    private static String getBoxedTypeName(TypeMirror type, Types typeUtils) {
        switch (type.getKind()) {
            case BOOLEAN:
                return "boolean";
            case BYTE:
                return "byte";
            case SHORT:
                return "short";
            case INT:
                return "int";
            case LONG:
                return "long";
            case FLOAT:
                return "float";
            case DOUBLE:
                return "double";
            case CHAR:
                return "char";
            default:
                return typeUtils.erasure(type).toString();
        }
    }

    private static String getGenericTypeArgument(TypeMirror type, int index, Types typeUtils) {
        if (type instanceof DeclaredType) {
            DeclaredType declaredType = (DeclaredType) type;
            List<? extends TypeMirror> typeArgs = declaredType.getTypeArguments();
            if (typeArgs.size() > index) {
                return typeArgs.get(index).toString();
            }
        }
        return "Object";
    }

    // --- String literal helpers ---

    private static String stringLiteral(String value) {
        if (value == null)
            return "null";
        return "\"" + escapeJavaString(value) + "\"";
    }

    private static String charLiteral(char value) {
        if (value == '\u0000')
            return "'\\u0000'";
        if (value == '\'')
            return "'\\''";
        if (value == '\\')
            return "'\\\\'";
        if (value == '\n')
            return "'\\n'";
        if (value == '\r')
            return "'\\r'";
        if (value == '\t')
            return "'\\t'";
        return "'" + value + "'";
    }

    private static String stringArrayLiteral(String[] values) {
        if (values == null || values.length == 0)
            return "";
        StringBuilder sb = new StringBuilder();
        for (int i = 0; i < values.length; i++) {
            if (i > 0)
                sb.append(", ");
            sb.append(stringLiteral(values[i]));
        }
        return sb.toString();
    }

    private static String stringArrayLiteralAsNew(String[] values) {
        if (values == null || values.length == 0) {
            return "new String[0]";
        }
        StringBuilder sb = new StringBuilder("new String[] {");
        for (int i = 0; i < values.length; i++) {
            if (i > 0)
                sb.append(", ");
            sb.append(stringLiteral(values[i]));
        }
        sb.append("}");
        return sb.toString();
    }

    private static String selectorLiteral(org.aesh.selector.SelectorType selectorType) {
        return "org.aesh.selector.SelectorType." + selectorType.name();
    }

    private static String escapeJavaString(String s) {
        StringBuilder sb = new StringBuilder();
        for (char c : s.toCharArray()) {
            switch (c) {
                case '"':
                    sb.append("\\\"");
                    break;
                case '\\':
                    sb.append("\\\\");
                    break;
                case '\n':
                    sb.append("\\n");
                    break;
                case '\r':
                    sb.append("\\r");
                    break;
                case '\t':
                    sb.append("\\t");
                    break;
                default:
                    sb.append(c);
            }
        }
        return sb.toString();
    }

    /**
     * Generate the {@code _AeshMetadataRegistry} source code.
     * <p>
     * The registry uses a {@code switch} statement on the command class's
     * binary name to lazily instantiate only the requested metadata provider
     * via a direct {@code new} call — no reflection, no lambdas.
     *
     * @param packageName the package for the registry class (may be empty)
     * @param entries list of (binaryClassName, metadataClassName) pairs
     * @return the generated Java source code
     */
    static String generateRegistry(String packageName, List<String[]> entries) {
        StringBuilder sb = new StringBuilder();

        if (!packageName.isEmpty()) {
            sb.append("package ").append(packageName).append(";\n\n");
        }

        sb.append("/**\n");
        sb.append(" * Generated metadata registry — maps command class names to their\n");
        sb.append(" * generated metadata providers via a switch statement.\n");
        sb.append(" * Do not edit — this file is regenerated by the aesh annotation processor.\n");
        sb.append(" */\n");
        sb.append("public final class _AeshMetadataRegistry implements org.aesh.command.metadata.MetadataRegistry {\n\n");

        sb.append("    @Override\n");
        sb.append("    public org.aesh.command.metadata.CommandMetadataProvider<?> get(String commandClassName) {\n");
        sb.append("        switch (commandClassName) {\n");
        for (String[] entry : entries) {
            sb.append("            case \"").append(entry[0]).append("\": return new ").append(entry[1]).append("();\n");
        }
        sb.append("            default: return null;\n");
        sb.append("        }\n");
        sb.append("    }\n");

        sb.append("}\n");

        return sb.toString();
    }
}
