/*
 * JBoss, Home of Professional Open Source
 * Copyright 2014 Red Hat Inc. and/or its affiliates and other contributors
 * as indicated by the @authors tag. All rights reserved.
 * See the copyright.txt in the distribution for a
 * full listing of individual contributors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * http://www.apache.org/licenses/LICENSE-2.0
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.aesh.processor;

import java.util.List;

import javax.lang.model.element.AnnotationMirror;
import javax.lang.model.element.AnnotationValue;
import javax.lang.model.element.ExecutableElement;
import javax.lang.model.element.TypeElement;
import javax.lang.model.element.VariableElement;
import javax.lang.model.type.DeclaredType;
import javax.lang.model.type.TypeKind;
import javax.lang.model.type.TypeMirror;
import javax.lang.model.util.Elements;
import javax.lang.model.util.Types;

import org.aesh.command.CommandDefinition;
import org.aesh.command.GroupCommandDefinition;
import org.aesh.command.option.Argument;
import org.aesh.command.option.Arguments;
import org.aesh.command.option.Mixin;
import org.aesh.command.option.Option;
import org.aesh.command.option.OptionGroup;
import org.aesh.command.option.OptionList;

/**
 * Generates Java source code for {@code CommandMetadataProvider} implementations.
 *
 * @author Aesh team
 */
final class CodeGenerator {

    // Sentinel class names — when annotation value equals these, skip the builder call
    private static final String NULL_COMMAND_VALIDATOR = "org.aesh.command.impl.validator.NullCommandValidator";
    private static final String NULL_RESULT_HANDLER = "org.aesh.command.impl.result.NullResultHandler";
    private static final String NULL_COMMAND_ACTIVATOR = "org.aesh.command.impl.activator.NullCommandActivator";
    private static final String NULL_OPTION_COMPLETER = "org.aesh.command.impl.completer.NullOptionCompleter";
    private static final String NULL_CONVERTER = "org.aesh.command.impl.converter.NullConverter";
    private static final String NULL_VALIDATOR = "org.aesh.command.impl.validator.NullValidator";
    private static final String NULL_ACTIVATOR = "org.aesh.command.impl.activator.NullActivator";
    private static final String NULL_OPTION_RENDERER = "org.aesh.command.impl.renderer.NullOptionRenderer";
    private static final String AESH_OPTION_PARSER = "org.aesh.command.impl.parser.AeshOptionParser";
    private static final String NULL_DEFAULT_VALUE_PROVIDER = "org.aesh.command.impl.provider.NullDefaultValueProvider";
    private static final String NULL_HELP_SECTION_PROVIDER = "org.aesh.command.impl.provider.NullHelpSectionProvider";

    private CodeGenerator() {
    }

    static String generate(
            String packageName, String simpleName, String metadataClassName,
            String qualifiedCommandName, TypeElement commandElement,
            List<VariableElement> fields, boolean isGroup,
            Elements elementUtils, Types typeUtils) {

        StringBuilder sb = new StringBuilder();

        // Package
        if (!packageName.isEmpty()) {
            sb.append("package ").append(packageName).append(";\n\n");
        }

        // Imports
        sb.append("import java.util.Arrays;\n");
        sb.append("import java.util.function.BiConsumer;\n");
        sb.append("import java.util.function.Consumer;\n\n");
        sb.append("import org.aesh.command.Command;\n");
        sb.append("import org.aesh.command.impl.internal.ProcessedCommand;\n");
        sb.append("import org.aesh.command.impl.internal.ProcessedCommandBuilder;\n");
        sb.append("import org.aesh.command.impl.internal.ProcessedOptionBuilder;\n");
        sb.append("import org.aesh.command.impl.internal.OptionType;\n");
        sb.append("import org.aesh.command.metadata.CommandMetadataProvider;\n");
        sb.append("import org.aesh.command.parser.CommandLineParserException;\n\n");

        // Class declaration
        sb.append("/**\n");
        sb.append(" * Generated compile-time metadata provider for {@link ").append(qualifiedCommandName).append("}.\n");
        sb.append(" * Do not edit — this file is regenerated by the aesh annotation processor.\n");
        sb.append(" */\n");
        sb.append("@SuppressWarnings({\"unchecked\", \"rawtypes\"})\n");
        sb.append("public final class ").append(metadataClassName);
        sb.append(" implements CommandMetadataProvider<").append(simpleName).append("> {\n\n");

        // commandType()
        sb.append("    @Override\n");
        sb.append("    public Class<").append(simpleName).append("> commandType() {\n");
        sb.append("        return ").append(simpleName).append(".class;\n");
        sb.append("    }\n\n");

        // newInstance()
        sb.append("    @Override\n");
        sb.append("    public ").append(simpleName).append(" newInstance() {\n");
        sb.append("        return new ").append(simpleName).append("();\n");
        sb.append("    }\n\n");

        // isGroupCommand()
        sb.append("    @Override\n");
        sb.append("    public boolean isGroupCommand() {\n");
        sb.append("        return ").append(isGroup).append(";\n");
        sb.append("    }\n\n");

        // groupCommandClasses()
        sb.append("    @Override\n");
        sb.append("    public Class<? extends Command>[] groupCommandClasses() {\n");
        if (isGroup) {
            generateGroupCommandClasses(sb, commandElement, elementUtils);
        } else {
            sb.append("        return new Class[0];\n");
        }
        sb.append("    }\n\n");

        // buildProcessedCommand()
        sb.append("    @Override\n");
        sb.append("    public ProcessedCommand buildProcessedCommand(").append(simpleName).append(" instance)");
        sb.append(" throws CommandLineParserException {\n");
        generateBuildProcessedCommand(sb, simpleName, commandElement, fields, isGroup, elementUtils, typeUtils);
        sb.append("    }\n");

        // End class
        sb.append("}\n");

        return sb.toString();
    }

    private static void generateGroupCommandClasses(StringBuilder sb, TypeElement commandElement, Elements elementUtils) {
        // We need to extract groupCommands() from @GroupCommandDefinition via annotation mirror
        // because accessing it directly would trigger MirroredTypesException at compile time.
        List<String> groupClasses = getGroupCommandClassNames(commandElement, elementUtils);
        if (groupClasses.isEmpty()) {
            sb.append("        return new Class[0];\n");
        } else {
            sb.append("        return new Class[] {\n");
            for (int i = 0; i < groupClasses.size(); i++) {
                sb.append("            ").append(groupClasses.get(i)).append(".class");
                if (i < groupClasses.size() - 1)
                    sb.append(",");
                sb.append("\n");
            }
            sb.append("        };\n");
        }
    }

    @SuppressWarnings("unchecked")
    private static List<String> getGroupCommandClassNames(TypeElement element, Elements elementUtils) {
        List<String> classNames = new java.util.ArrayList<>();
        for (AnnotationMirror mirror : element.getAnnotationMirrors()) {
            String annotationType = ((TypeElement) mirror.getAnnotationType().asElement())
                    .getQualifiedName().toString();
            if (annotationType.equals(GroupCommandDefinition.class.getCanonicalName())) {
                for (java.util.Map.Entry<? extends ExecutableElement, ? extends AnnotationValue> entry : mirror
                        .getElementValues().entrySet()) {
                    if (entry.getKey().getSimpleName().toString().equals("groupCommands")) {
                        List<? extends AnnotationValue> values = (List<? extends AnnotationValue>) entry.getValue().getValue();
                        for (AnnotationValue av : values) {
                            TypeMirror tm = (TypeMirror) av.getValue();
                            classNames.add(tm.toString());
                        }
                    }
                }
            }
        }
        return classNames;
    }

    private static void generateBuildProcessedCommand(StringBuilder sb, String simpleName, TypeElement commandElement,
            List<VariableElement> fields, boolean isGroup,
            Elements elementUtils, Types typeUtils) {

        sb.append(
                "        ProcessedCommand processedCommand = ((ProcessedCommandBuilder) ProcessedCommandBuilder.builder())\n");

        if (isGroup) {
            GroupCommandDefinition gcd = commandElement.getAnnotation(GroupCommandDefinition.class);
            sb.append("                .name(").append(stringLiteral(gcd.name())).append(")\n");
            generateCommandActivator(sb, commandElement, isGroup, elementUtils);
            sb.append("                .aliases(Arrays.asList(").append(stringArrayLiteral(gcd.aliases())).append("))\n");
            sb.append("                .description(").append(stringLiteral(gcd.description())).append(")\n");
            generateCommandValidator(sb, commandElement, isGroup, elementUtils);
            sb.append("                .command(instance)\n");
            sb.append("                .generateHelp(").append(gcd.generateHelp()).append(")\n");
            sb.append("                .stopAtFirstPositional(").append(gcd.stopAtFirstPositional()).append(")\n");
            generateDefaultValueProvider(sb, commandElement, isGroup, elementUtils);
            sb.append("                .version(").append(stringLiteral(gcd.version())).append(")\n");
            generateResultHandler(sb, commandElement, isGroup, elementUtils);
            sb.append("                .helpUrl(").append(stringLiteral(gcd.helpUrl())).append(")\n");
        } else {
            CommandDefinition cd = commandElement.getAnnotation(CommandDefinition.class);
            sb.append("                .name(").append(stringLiteral(cd.name())).append(")\n");
            generateCommandActivator(sb, commandElement, isGroup, elementUtils);
            sb.append("                .aliases(Arrays.asList(").append(stringArrayLiteral(cd.aliases())).append("))\n");
            sb.append("                .description(").append(stringLiteral(cd.description())).append(")\n");
            generateCommandValidator(sb, commandElement, isGroup, elementUtils);
            sb.append("                .command(instance)\n");
            generateResultHandler(sb, commandElement, isGroup, elementUtils);
            sb.append("                .generateHelp(").append(cd.generateHelp()).append(")\n");
            sb.append("                .disableParsing(").append(cd.disableParsing()).append(")\n");
            sb.append("                .stopAtFirstPositional(").append(cd.stopAtFirstPositional()).append(")\n");
            generateDefaultValueProvider(sb, commandElement, isGroup, elementUtils);
            sb.append("                .version(").append(stringLiteral(cd.version())).append(")\n");
            sb.append("                .helpUrl(").append(stringLiteral(cd.helpUrl())).append(")\n");
        }

        sb.append("                .create();\n\n");

        // Set command-level helpGroup if present
        String cmdHelpGroup = isGroup
                ? commandElement.getAnnotation(GroupCommandDefinition.class).helpGroup()
                : commandElement.getAnnotation(CommandDefinition.class).helpGroup();
        if (!cmdHelpGroup.isEmpty()) {
            sb.append("        processedCommand.setHelpGroup(")
                    .append(stringLiteral(cmdHelpGroup)).append(");\n\n");
        }

        // Set helpSectionProvider if not NullHelpSectionProvider
        String providerClass = getAnnotationClassValue(commandElement,
                isGroup ? GroupCommandDefinition.class.getCanonicalName() : CommandDefinition.class.getCanonicalName(),
                "helpSectionProvider", elementUtils);
        if (providerClass != null && !providerClass.equals(NULL_HELP_SECTION_PROVIDER)) {
            sb.append("        processedCommand.setHelpSectionProviderClass(")
                    .append(providerClass).append(".class);\n\n");
        }

        // Process fields
        for (VariableElement field : fields) {
            generateFieldProcessing(sb, simpleName, field, elementUtils, typeUtils);
        }

        sb.append("        return processedCommand;\n");
    }

    private static void generateCommandValidator(StringBuilder sb, TypeElement element, boolean isGroup,
            Elements elementUtils) {
        String validatorClass = getAnnotationClassValue(element,
                isGroup ? GroupCommandDefinition.class.getCanonicalName() : CommandDefinition.class.getCanonicalName(),
                "validator", elementUtils);
        if (validatorClass != null && !validatorClass.equals(NULL_COMMAND_VALIDATOR)) {
            sb.append("                .validator(new ").append(validatorClass).append("())\n");
        }
    }

    private static void generateResultHandler(StringBuilder sb, TypeElement element, boolean isGroup,
            Elements elementUtils) {
        String handlerClass = getAnnotationClassValue(element,
                isGroup ? GroupCommandDefinition.class.getCanonicalName() : CommandDefinition.class.getCanonicalName(),
                "resultHandler", elementUtils);
        if (handlerClass != null && !handlerClass.equals(NULL_RESULT_HANDLER)) {
            sb.append("                .resultHandler(new ").append(handlerClass).append("())\n");
        }
    }

    private static void generateDefaultValueProvider(StringBuilder sb, TypeElement element, boolean isGroup,
            Elements elementUtils) {
        String providerClass = getAnnotationClassValue(element,
                isGroup ? GroupCommandDefinition.class.getCanonicalName() : CommandDefinition.class.getCanonicalName(),
                "defaultValueProvider", elementUtils);
        if (providerClass != null && !providerClass.equals(NULL_DEFAULT_VALUE_PROVIDER)) {
            sb.append("                .defaultValueProvider(new ").append(providerClass).append("())\n");
        }
    }

    private static void generateCommandActivator(StringBuilder sb, TypeElement element, boolean isGroup,
            Elements elementUtils) {
        String activatorClass = getAnnotationClassValue(element,
                isGroup ? GroupCommandDefinition.class.getCanonicalName() : CommandDefinition.class.getCanonicalName(),
                "activator", elementUtils);
        if (activatorClass != null && !activatorClass.equals(NULL_COMMAND_ACTIVATOR)) {
            sb.append("                .activator(new ").append(activatorClass).append("())\n");
        }
    }

    private static void generateFieldProcessing(StringBuilder sb, String simpleName, VariableElement field,
            Elements elementUtils, Types typeUtils) {
        generateFieldProcessing(sb, simpleName, field, null, elementUtils, typeUtils);
    }

    private static void generateFieldProcessing(StringBuilder sb, String simpleName, VariableElement field,
            String mixinFieldName, Elements elementUtils, Types typeUtils) {
        Option o = field.getAnnotation(Option.class);
        OptionList ol = field.getAnnotation(OptionList.class);
        OptionGroup og = field.getAnnotation(OptionGroup.class);
        Arguments args = field.getAnnotation(Arguments.class);
        Argument arg = field.getAnnotation(Argument.class);

        if (o != null) {
            generateOption(sb, simpleName, field, o, mixinFieldName, elementUtils, typeUtils);
        } else if (ol != null) {
            generateOptionList(sb, simpleName, field, ol, mixinFieldName, elementUtils, typeUtils);
        } else if (og != null) {
            generateOptionGroup(sb, simpleName, field, og, mixinFieldName, elementUtils, typeUtils);
        } else if (args != null) {
            generateArguments(sb, simpleName, field, args, mixinFieldName, elementUtils, typeUtils);
        } else if (arg != null) {
            generateArgument(sb, simpleName, field, arg, mixinFieldName, elementUtils, typeUtils);
        } else if (field.getAnnotation(Mixin.class) != null) {
            generateMixin(sb, simpleName, field, elementUtils, typeUtils);
        }
    }

    private static void generateMixin(StringBuilder sb, String simpleName, VariableElement mixinField,
            Elements elementUtils, Types typeUtils) {
        String mixinFieldName = mixinField.getSimpleName().toString();
        TypeMirror mixinType = mixinField.asType();
        if (!(mixinType instanceof DeclaredType))
            return;
        TypeElement mixinElement = (TypeElement) ((DeclaredType) mixinType).asElement();
        String mixinTypeName = mixinType.toString();

        if (isAccessibleField(mixinField)) {
            sb.append("        if (instance.").append(mixinFieldName).append(" == null) {\n");
            sb.append("            instance.").append(mixinFieldName).append(" = new ").append(mixinTypeName)
                    .append("();\n");
            sb.append("        }\n\n");
        }

        generateMixinFields(sb, simpleName, mixinFieldName, mixinElement, elementUtils, typeUtils);
    }

    private static void generateMixinFields(StringBuilder sb, String simpleName, String mixinFieldName,
            TypeElement typeElement, Elements elementUtils, Types typeUtils) {
        for (javax.lang.model.element.Element enclosed : typeElement.getEnclosedElements()) {
            if (enclosed instanceof VariableElement) {
                generateFieldProcessing(sb, simpleName, (VariableElement) enclosed, mixinFieldName,
                        elementUtils, typeUtils);
            }
        }
        // Recurse into superclass
        TypeMirror superclass = typeElement.getSuperclass();
        if (superclass.getKind() != TypeKind.NONE && !superclass.toString().equals("java.lang.Object")) {
            if (superclass instanceof DeclaredType) {
                TypeElement superElement = (TypeElement) ((DeclaredType) superclass).asElement();
                generateMixinFields(sb, simpleName, mixinFieldName, superElement, elementUtils, typeUtils);
            }
        }
    }

    private static void generateOption(StringBuilder sb, String simpleName, VariableElement field, Option o,
            String mixinFieldName, Elements elementUtils, Types typeUtils) {
        String fieldName = field.getSimpleName().toString();
        String fieldType = getBoxedTypeName(field.asType(), typeUtils);
        boolean isBooleanType = isBooleanType(field.asType(), typeUtils);

        String optionType;
        if (o.hasValue()) {
            optionType = "OptionType.NORMAL";
        } else {
            optionType = "OptionType.BOOLEAN";
        }

        sb.append("        processedCommand.addOption(\n");
        sb.append("                ProcessedOptionBuilder.builder()\n");
        sb.append("                        .shortName(").append(charLiteral(o.shortName())).append(")\n");
        sb.append("                        .name(").append(stringLiteral(o.name().length() < 1 ? fieldName : o.name()))
                .append(")\n");
        sb.append("                        .description(").append(stringLiteral(o.description())).append(")\n");
        sb.append("                        .required(").append(o.required()).append(")\n");
        sb.append("                        .valueSeparator(' ')\n");
        sb.append("                        .askIfNotSet(").append(o.askIfNotSet()).append(")\n");
        sb.append("                        .acceptNameWithoutDashes(").append(o.acceptNameWithoutDashes()).append(")\n");
        sb.append("                        .selector(").append(selectorLiteral(o.selector())).append(")\n");
        sb.append("                        .addAllDefaultValues(").append(stringArrayLiteralAsNew(o.defaultValue()))
                .append(")\n");
        sb.append("                        .type(").append(fieldType).append(".class)\n");
        sb.append("                        .fieldName(").append(stringLiteral(fieldName)).append(")\n");
        sb.append("                        .optionType(").append(optionType).append(")\n");
        generateOptionConverter(sb, field, "converter", elementUtils);
        generateOptionCompleter(sb, field, "completer", isBooleanType, isFileOrResourceType(field.asType(), typeUtils),
                elementUtils);
        generateOptionValidator(sb, field, "validator", elementUtils);
        generateOptionActivator(sb, field, "activator", elementUtils);
        generateOptionRenderer(sb, field, "renderer", elementUtils);
        generateOptionParser(sb, field, "parser", elementUtils);
        sb.append("                        .overrideRequired(").append(o.overrideRequired()).append(")\n");
        sb.append("                        .optionalValue(").append(o.optionalValue()).append(")\n");
        sb.append("                        .negatable(").append(o.negatable()).append(")\n");
        sb.append("                        .negationPrefix(").append(stringLiteral(o.negationPrefix())).append(")\n");
        sb.append("                        .inherited(").append(o.inherited()).append(")\n");
        sb.append("                        .descriptionUrl(").append(stringLiteral(o.descriptionUrl())).append(")\n");
        sb.append("                        .url(").append(o.url()).append(")\n");
        generateAliases(sb, o.aliases());
        generateHelpGroup(sb, o.helpGroup());
        generateFieldAccessors(sb, simpleName, field, mixinFieldName, typeUtils);
        sb.append("                        .build());\n\n");
    }

    private static void generateOptionList(StringBuilder sb, String simpleName, VariableElement field, OptionList ol,
            String mixinFieldName, Elements elementUtils, Types typeUtils) {
        String fieldName = field.getSimpleName().toString();
        String elementType = getGenericTypeArgument(field.asType(), 0, typeUtils);

        sb.append("        processedCommand.addOption(\n");
        sb.append("                ProcessedOptionBuilder.builder()\n");
        sb.append("                        .shortName(").append(charLiteral(ol.shortName())).append(")\n");
        sb.append("                        .name(").append(stringLiteral(ol.name().length() < 1 ? fieldName : ol.name()))
                .append(")\n");
        sb.append("                        .description(").append(stringLiteral(ol.description())).append(")\n");
        sb.append("                        .required(").append(ol.required()).append(")\n");
        sb.append("                        .valueSeparator(").append(charLiteral(ol.valueSeparator())).append(")\n");
        sb.append("                        .askIfNotSet(").append(ol.askIfNotSet()).append(")\n");
        sb.append("                        .selector(").append(selectorLiteral(ol.selector())).append(")\n");
        sb.append("                        .addAllDefaultValues(").append(stringArrayLiteralAsNew(ol.defaultValue()))
                .append(")\n");
        sb.append("                        .type(").append(elementType).append(".class)\n");
        sb.append("                        .fieldName(").append(stringLiteral(fieldName)).append(")\n");
        sb.append("                        .optionType(OptionType.LIST)\n");
        generateOptionConverter(sb, field, "converter", elementUtils);
        generateOptionCompleter(sb, field, "completer", false, false, elementUtils);
        generateOptionValidator(sb, field, "validator", elementUtils);
        generateOptionActivator(sb, field, "activator", elementUtils);
        generateOptionRenderer(sb, field, "renderer", elementUtils);
        generateOptionParser(sb, field, "parser", elementUtils);
        generateAliases(sb, ol.aliases());
        generateHelpGroup(sb, ol.helpGroup());
        generateFieldAccessors(sb, simpleName, field, mixinFieldName, typeUtils);
        sb.append("                        .build());\n\n");
    }

    private static void generateOptionGroup(StringBuilder sb, String simpleName, VariableElement field, OptionGroup og,
            String mixinFieldName, Elements elementUtils, Types typeUtils) {
        String fieldName = field.getSimpleName().toString();
        // For Map<K,V>, extract V (index 1)
        String valueType = getGenericTypeArgument(field.asType(), 1, typeUtils);

        sb.append("        processedCommand.addOption(\n");
        sb.append("                ProcessedOptionBuilder.builder()\n");
        sb.append("                        .shortName(").append(charLiteral(og.shortName())).append(")\n");
        sb.append("                        .name(").append(stringLiteral(og.name().length() < 1 ? fieldName : og.name()))
                .append(")\n");
        sb.append("                        .description(").append(stringLiteral(og.description())).append(")\n");
        sb.append("                        .required(").append(og.required()).append(")\n");
        sb.append("                        .valueSeparator(',')\n");
        sb.append("                        .askIfNotSet(").append(og.askIfNotSet()).append(")\n");
        sb.append("                        .addAllDefaultValues(").append(stringArrayLiteralAsNew(og.defaultValue()))
                .append(")\n");
        sb.append("                        .type(").append(valueType).append(".class)\n");
        sb.append("                        .fieldName(").append(stringLiteral(fieldName)).append(")\n");
        sb.append("                        .optionType(OptionType.GROUP)\n");
        generateOptionConverter(sb, field, "converter", elementUtils);
        generateOptionCompleter(sb, field, "completer", false, false, elementUtils);
        generateOptionValidator(sb, field, "validator", elementUtils);
        generateOptionActivator(sb, field, "activator", elementUtils);
        generateOptionRenderer(sb, field, "renderer", elementUtils);
        generateOptionParser(sb, field, "parser", elementUtils);
        generateFieldAccessors(sb, simpleName, field, mixinFieldName, typeUtils);
        sb.append("                        .build());\n\n");
    }

    private static void generateArguments(StringBuilder sb, String simpleName, VariableElement field, Arguments a,
            String mixinFieldName, Elements elementUtils, Types typeUtils) {
        String fieldName = field.getSimpleName().toString();
        String elementType = getGenericTypeArgument(field.asType(), 0, typeUtils);

        sb.append("        processedCommand.setArguments(\n");
        sb.append("                ProcessedOptionBuilder.builder()\n");
        sb.append("                        .shortName('\\u0000')\n");
        sb.append("                        .name(\"\")\n");
        sb.append("                        .description(").append(stringLiteral(a.description())).append(")\n");
        sb.append("                        .required(").append(a.required()).append(")\n");
        sb.append("                        .valueSeparator(").append(charLiteral(a.valueSeparator())).append(")\n");
        sb.append("                        .selector(").append(selectorLiteral(a.selector())).append(")\n");
        sb.append("                        .askIfNotSet(").append(a.askIfNotSet()).append(")\n");
        sb.append("                        .addAllDefaultValues(").append(stringArrayLiteralAsNew(a.defaultValue()))
                .append(")\n");
        sb.append("                        .type(").append(elementType).append(".class)\n");
        sb.append("                        .fieldName(").append(stringLiteral(fieldName)).append(")\n");
        sb.append("                        .optionType(OptionType.ARGUMENTS)\n");
        generateOptionConverter(sb, field, "converter", elementUtils);
        generateOptionCompleter(sb, field, "completer", false, false, elementUtils);
        generateOptionValidator(sb, field, "validator", elementUtils);
        generateOptionActivator(sb, field, "activator", elementUtils);
        generateOptionParser(sb, field, "parser", elementUtils);
        sb.append("                        .url(").append(a.url()).append(")\n");
        generateFieldAccessors(sb, simpleName, field, mixinFieldName, typeUtils);
        sb.append("                        .build());\n\n");
    }

    private static void generateArgument(StringBuilder sb, String simpleName, VariableElement field, Argument arg,
            String mixinFieldName, Elements elementUtils, Types typeUtils) {
        String fieldName = field.getSimpleName().toString();
        String fieldType = getBoxedTypeName(field.asType(), typeUtils);

        sb.append("        processedCommand.setArgument(\n");
        sb.append("                ProcessedOptionBuilder.builder()\n");
        sb.append("                        .shortName('\\u0000')\n");
        sb.append("                        .name(\"\")\n");
        sb.append("                        .description(").append(stringLiteral(arg.description())).append(")\n");
        sb.append("                        .required(").append(arg.required()).append(")\n");
        sb.append("                        .valueSeparator(' ')\n");
        sb.append("                        .askIfNotSet(").append(arg.askIfNotSet()).append(")\n");
        sb.append("                        .selector(").append(selectorLiteral(arg.selector())).append(")\n");
        sb.append("                        .addAllDefaultValues(").append(stringArrayLiteralAsNew(arg.defaultValue()))
                .append(")\n");
        sb.append("                        .type(").append(fieldType).append(".class)\n");
        sb.append("                        .fieldName(").append(stringLiteral(fieldName)).append(")\n");
        sb.append("                        .optionType(OptionType.ARGUMENT)\n");
        generateOptionConverter(sb, field, "converter", elementUtils);
        generateOptionCompleter(sb, field, "completer", false, isFileOrResourceType(field.asType(), typeUtils), elementUtils);
        generateOptionValidator(sb, field, "validator", elementUtils);
        generateOptionActivator(sb, field, "activator", elementUtils);
        generateOptionRenderer(sb, field, "renderer", elementUtils);
        generateOptionParser(sb, field, "parser", elementUtils);
        sb.append("                        .overrideRequired(").append(arg.overrideRequired()).append(")\n");
        sb.append("                        .inherited(").append(arg.inherited()).append(")\n");
        sb.append("                        .url(").append(arg.url()).append(")\n");
        generateFieldAccessors(sb, simpleName, field, mixinFieldName, typeUtils);
        sb.append("                        .build());\n\n");
    }

    private static void generateFieldAccessors(StringBuilder sb, String simpleName, VariableElement field,
            String mixinFieldName, Types typeUtils) {
        if (mixinFieldName != null) {
            sb.append("                        .mixinFieldName(").append(stringLiteral(mixinFieldName)).append(")\n");
            generateMixinFieldSetter(sb, simpleName, field, mixinFieldName, typeUtils);
            generateMixinFieldResetter(sb, simpleName, field, mixinFieldName, typeUtils);
            generateMixinFieldGetter(sb, simpleName, field, mixinFieldName);
        } else {
            generateFieldSetter(sb, simpleName, field, typeUtils);
            generateFieldResetter(sb, simpleName, field, typeUtils);
            generateFieldGetter(sb, simpleName, field);
        }
    }

    private static void generateAliases(StringBuilder sb, String[] aliases) {
        if (aliases != null && aliases.length > 0) {
            sb.append("                        .aliases(").append(stringArrayLiteralAsNew(aliases)).append(")\n");
        }
    }

    private static void generateHelpGroup(StringBuilder sb, String helpGroup) {
        if (helpGroup != null && !helpGroup.isEmpty()) {
            sb.append("                        .helpGroup(").append(stringLiteral(helpGroup)).append(")\n");
        }
    }

    // --- Helper methods for generating option component instantiation ---

    private static void generateOptionConverter(StringBuilder sb, VariableElement field,
            String attributeName, Elements elementUtils) {
        String className = getFieldAnnotationClassValue(field, attributeName, elementUtils);
        if (className != null && !className.equals(NULL_CONVERTER)) {
            sb.append("                        .converter(new ").append(className).append("())\n");
        } else {
            // Pass the Class so the builder can resolve via CLConverterManager
            sb.append("                        .converter(").append(className != null ? className : NULL_CONVERTER)
                    .append(".class)\n");
        }
    }

    private static void generateOptionCompleter(StringBuilder sb, VariableElement field,
            String attributeName, boolean isBooleanType, boolean isFileOrResource, Elements elementUtils) {
        String className = getFieldAnnotationClassValue(field, attributeName, elementUtils);
        if (className != null && !className.equals(NULL_OPTION_COMPLETER)) {
            sb.append("                        .completer(new ").append(className).append("())\n");
        } else if (isBooleanType) {
            sb.append("                        .completer(new org.aesh.command.impl.completer.BooleanOptionCompleter())\n");
        } else if (isFileOrResource) {
            sb.append("                        .completer(new org.aesh.command.impl.completer.FileOptionCompleter())\n");
        } else {
            sb.append("                        .completer(").append(NULL_OPTION_COMPLETER).append(".class)\n");
        }
    }

    private static void generateOptionValidator(StringBuilder sb, VariableElement field,
            String attributeName, Elements elementUtils) {
        String className = getFieldAnnotationClassValue(field, attributeName, elementUtils);
        if (className != null && !className.equals(NULL_VALIDATOR)) {
            sb.append("                        .validator(new ").append(className).append("())\n");
        } else {
            sb.append("                        .validator(").append(NULL_VALIDATOR).append(".class)\n");
        }
    }

    private static void generateOptionActivator(StringBuilder sb, VariableElement field,
            String attributeName, Elements elementUtils) {
        String className = getFieldAnnotationClassValue(field, attributeName, elementUtils);
        if (className != null && !className.equals(NULL_ACTIVATOR)) {
            sb.append("                        .activator(new ").append(className).append("())\n");
        } else {
            sb.append("                        .activator(").append(NULL_ACTIVATOR).append(".class)\n");
        }
    }

    private static void generateOptionRenderer(StringBuilder sb, VariableElement field,
            String attributeName, Elements elementUtils) {
        String className = getFieldAnnotationClassValue(field, attributeName, elementUtils);
        if (className != null && !className.equals(NULL_OPTION_RENDERER)) {
            sb.append("                        .renderer(new ").append(className).append("())\n");
        } else {
            sb.append("                        .renderer(").append(NULL_OPTION_RENDERER).append(".class)\n");
        }
    }

    private static void generateOptionParser(StringBuilder sb, VariableElement field,
            String attributeName, Elements elementUtils) {
        String className = getFieldAnnotationClassValue(field, attributeName, elementUtils);
        if (className != null && !className.equals(AESH_OPTION_PARSER)) {
            sb.append("                        .parser(new ").append(className).append("())\n");
        } else {
            sb.append("                        .parser(").append(AESH_OPTION_PARSER).append(".class)\n");
        }
    }

    // --- Annotation class value extraction (handles MirroredTypeException) ---

    /**
     * Extract the Class value of a named annotation attribute from the field's
     * option annotation. Returns the fully-qualified class name, or null if not found.
     */
    private static String getFieldAnnotationClassValue(VariableElement field, String attributeName,
            Elements elementUtils) {
        // Check which annotation is on this field and extract from it
        String[] annotationTypes = {
                Option.class.getCanonicalName(),
                OptionList.class.getCanonicalName(),
                OptionGroup.class.getCanonicalName(),
                Arguments.class.getCanonicalName(),
                Argument.class.getCanonicalName()
        };

        for (AnnotationMirror mirror : field.getAnnotationMirrors()) {
            String annotationType = ((TypeElement) mirror.getAnnotationType().asElement())
                    .getQualifiedName().toString();
            for (String expected : annotationTypes) {
                if (annotationType.equals(expected)) {
                    return extractClassAttribute(mirror, attributeName);
                }
            }
        }
        return null;
    }

    private static String getAnnotationClassValue(TypeElement element, String annotationType,
            String attributeName, Elements elementUtils) {
        for (AnnotationMirror mirror : element.getAnnotationMirrors()) {
            String mirrorType = ((TypeElement) mirror.getAnnotationType().asElement())
                    .getQualifiedName().toString();
            if (mirrorType.equals(annotationType)) {
                return extractClassAttribute(mirror, attributeName);
            }
        }
        return null;
    }

    private static String extractClassAttribute(AnnotationMirror mirror, String attributeName) {
        for (java.util.Map.Entry<? extends ExecutableElement, ? extends AnnotationValue> entry : mirror.getElementValues()
                .entrySet()) {
            if (entry.getKey().getSimpleName().toString().equals(attributeName)) {
                Object value = entry.getValue().getValue();
                if (value instanceof TypeMirror) {
                    return ((TypeMirror) value).toString();
                }
            }
        }
        return null;
    }

    // --- Type utility methods ---

    private static boolean isBooleanType(TypeMirror type, Types typeUtils) {
        if (type.getKind() == TypeKind.BOOLEAN)
            return true;
        String name = type.toString();
        return name.equals("java.lang.Boolean");
    }

    private static boolean isFileOrResourceType(TypeMirror type, Types typeUtils) {
        String name = type.toString();
        return name.equals("java.io.File") || name.equals("org.aesh.io.Resource");
    }

    private static String getBoxedTypeName(TypeMirror type, Types typeUtils) {
        switch (type.getKind()) {
            case BOOLEAN:
                return "boolean";
            case BYTE:
                return "byte";
            case SHORT:
                return "short";
            case INT:
                return "int";
            case LONG:
                return "long";
            case FLOAT:
                return "float";
            case DOUBLE:
                return "double";
            case CHAR:
                return "char";
            default:
                return typeUtils.erasure(type).toString();
        }
    }

    private static String getGenericTypeArgument(TypeMirror type, int index, Types typeUtils) {
        if (type instanceof DeclaredType) {
            DeclaredType declaredType = (DeclaredType) type;
            List<? extends TypeMirror> typeArgs = declaredType.getTypeArguments();
            if (typeArgs.size() > index) {
                return typeArgs.get(index).toString();
            }
        }
        return "Object";
    }

    // --- String literal helpers ---

    private static String stringLiteral(String value) {
        if (value == null)
            return "null";
        return "\"" + escapeJavaString(value) + "\"";
    }

    private static String charLiteral(char value) {
        if (value == '\u0000')
            return "'\\u0000'";
        if (value == '\'')
            return "'\\''";
        if (value == '\\')
            return "'\\\\'";
        if (value == '\n')
            return "'\\n'";
        if (value == '\r')
            return "'\\r'";
        if (value == '\t')
            return "'\\t'";
        return "'" + value + "'";
    }

    private static String stringArrayLiteral(String[] values) {
        if (values == null || values.length == 0)
            return "";
        StringBuilder sb = new StringBuilder();
        for (int i = 0; i < values.length; i++) {
            if (i > 0)
                sb.append(", ");
            sb.append(stringLiteral(values[i]));
        }
        return sb.toString();
    }

    private static String stringArrayLiteralAsNew(String[] values) {
        if (values == null || values.length == 0) {
            return "new String[0]";
        }
        StringBuilder sb = new StringBuilder("new String[] {");
        for (int i = 0; i < values.length; i++) {
            if (i > 0)
                sb.append(", ");
            sb.append(stringLiteral(values[i]));
        }
        sb.append("}");
        return sb.toString();
    }

    private static String selectorLiteral(org.aesh.selector.SelectorType selectorType) {
        return "org.aesh.selector.SelectorType." + selectorType.name();
    }

    private static boolean isAccessibleField(VariableElement field) {
        java.util.Set<javax.lang.model.element.Modifier> modifiers = field.getModifiers();
        return !modifiers.contains(javax.lang.model.element.Modifier.PRIVATE);
    }

    private static void generateMixinFieldSetter(StringBuilder sb, String commandSimpleName, VariableElement field,
            String mixinFieldName, Types typeUtils) {
        if (!isAccessibleField(field))
            return;
        String fieldName = field.getSimpleName().toString();
        String fieldType = field.asType().toString();

        sb.append("                        .fieldSetter((inst, val) -> { if (((").append(commandSimpleName)
                .append(") inst).").append(mixinFieldName).append(" != null) ((").append(commandSimpleName)
                .append(") inst).").append(mixinFieldName).append(".").append(fieldName)
                .append(" = (").append(fieldType).append(") val; })\n");
    }

    private static void generateMixinFieldResetter(StringBuilder sb, String commandSimpleName, VariableElement field,
            String mixinFieldName, Types typeUtils) {
        if (!isAccessibleField(field))
            return;
        String fieldName = field.getSimpleName().toString();
        TypeMirror fieldType = field.asType();

        sb.append("                        .fieldResetter(inst -> { if (((").append(commandSimpleName)
                .append(") inst).").append(mixinFieldName).append(" != null) ((")
                .append(commandSimpleName).append(") inst).")
                .append(mixinFieldName).append(".").append(fieldName).append(" = ");

        switch (fieldType.getKind()) {
            case BOOLEAN:
                sb.append("false");
                break;
            case BYTE:
                sb.append("(byte) 0");
                break;
            case SHORT:
                sb.append("(short) 0");
                break;
            case INT:
                sb.append("0");
                break;
            case LONG:
                sb.append("0L");
                break;
            case FLOAT:
                sb.append("0.0f");
                break;
            case DOUBLE:
                sb.append("0.0d");
                break;
            case CHAR:
                sb.append("'\\u0000'");
                break;
            default:
                sb.append("null");
                break;
        }
        sb.append("; })\n");
    }

    private static void generateFieldGetter(StringBuilder sb, String commandSimpleName, VariableElement field) {
        if (!isAccessibleField(field))
            return;
        String fieldName = field.getSimpleName().toString();
        sb.append("                        .fieldGetter(inst -> ((").append(commandSimpleName).append(") inst).")
                .append(fieldName).append(")\n");
    }

    private static void generateMixinFieldGetter(StringBuilder sb, String commandSimpleName, VariableElement field,
            String mixinFieldName) {
        if (!isAccessibleField(field))
            return;
        String fieldName = field.getSimpleName().toString();
        sb.append("                        .fieldGetter(inst -> ((").append(commandSimpleName)
                .append(") inst).").append(mixinFieldName)
                .append(" != null ? ((").append(commandSimpleName).append(") inst).")
                .append(mixinFieldName).append(".").append(fieldName).append(" : null)\n");
    }

    private static void generateFieldSetter(StringBuilder sb, String commandSimpleName, VariableElement field,
            Types typeUtils) {
        if (!isAccessibleField(field))
            return;
        String fieldName = field.getSimpleName().toString();
        String fieldType = field.asType().toString();

        sb.append("                        .fieldSetter((inst, val) -> ((").append(commandSimpleName).append(") inst).")
                .append(fieldName).append(" = (").append(fieldType).append(") val)\n");
    }

    private static void generateFieldResetter(StringBuilder sb, String commandSimpleName, VariableElement field,
            Types typeUtils) {
        if (!isAccessibleField(field))
            return;
        String fieldName = field.getSimpleName().toString();
        TypeMirror fieldType = field.asType();

        sb.append("                        .fieldResetter(inst -> ((").append(commandSimpleName).append(") inst).")
                .append(fieldName).append(" = ");

        switch (fieldType.getKind()) {
            case BOOLEAN:
                sb.append("false");
                break;
            case BYTE:
                sb.append("(byte) 0");
                break;
            case SHORT:
                sb.append("(short) 0");
                break;
            case INT:
                sb.append("0");
                break;
            case LONG:
                sb.append("0L");
                break;
            case FLOAT:
                sb.append("0.0f");
                break;
            case DOUBLE:
                sb.append("0.0d");
                break;
            case CHAR:
                sb.append("'\\u0000'");
                break;
            default:
                sb.append("null");
                break;
        }
        sb.append(")\n");
    }

    private static String escapeJavaString(String s) {
        StringBuilder sb = new StringBuilder();
        for (char c : s.toCharArray()) {
            switch (c) {
                case '"':
                    sb.append("\\\"");
                    break;
                case '\\':
                    sb.append("\\\\");
                    break;
                case '\n':
                    sb.append("\\n");
                    break;
                case '\r':
                    sb.append("\\r");
                    break;
                case '\t':
                    sb.append("\\t");
                    break;
                default:
                    sb.append(c);
            }
        }
        return sb.toString();
    }
}
