/*
 * JBoss, Home of Professional Open Source
 * Copyright 2014 Red Hat Inc. and/or its affiliates and other contributors
 * as indicated by the @authors tag
 * See the copyright.txt in the distribution for a
 * full listing of individual contributors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.aesh.util.completer;

import java.util.ArrayList;
import java.util.List;

import org.aesh.command.impl.internal.ProcessedOption;
import org.aesh.command.impl.parser.CommandLineParser;
import org.aesh.command.invocation.CommandInvocation;

/**
 * Generates fish shell completion scripts.
 *
 * @author Aesh team
 */
public class FishCompletionGenerator implements ShellCompletionGenerator {

    private static final String NL = "\n";

    @Override
    public String generate(CommandLineParser<? extends CommandInvocation> parser, String programName) {
        StringBuilder out = new StringBuilder();
        out.append("# Fish completion for ").append(programName).append(" — generated by Aesh.").append(NL);
        out.append("# Place this file in ~/.config/fish/completions/").append(programName).append(".fish").append(NL);
        out.append(NL);

        if (parser.isGroupCommand()) {
            generateGroupCommand(out, parser, programName);
        } else {
            generateSimpleCommand(out, parser, programName, null);
        }

        return out.toString();
    }

    private void generateGroupCommand(StringBuilder out,
            CommandLineParser<? extends CommandInvocation> parser, String programName) {

        List<String> subcommandNames = new ArrayList<>();
        for (CommandLineParser<? extends CommandInvocation> child : parser.getAllChildParsers()) {
            subcommandNames.add(child.getProcessedCommand().name().toLowerCase());
        }

        for (ProcessedOption option : parser.getProcessedCommand().getOptions()) {
            if (option.isProperty())
                continue;
            appendFishOption(out, programName, null, option);
        }
        out.append(NL);

        for (CommandLineParser<? extends CommandInvocation> child : parser.getAllChildParsers()) {
            String childName = child.getProcessedCommand().name().toLowerCase();
            String desc = escapeFish(child.getProcessedCommand().description());
            out.append("complete -c ").append(programName).append(" -f")
                    .append(" -n \"__fish_use_subcommand\"")
                    .append(" -a ").append(childName);
            if (!desc.isEmpty())
                out.append(" -d '").append(desc).append("'");
            out.append(NL);
        }
        out.append(NL);

        for (CommandLineParser<? extends CommandInvocation> child : parser.getAllChildParsers()) {
            String childName = child.getProcessedCommand().name().toLowerCase();
            generateSimpleCommand(out, child, programName, childName);

            if (child.isGroupCommand()) {
                List<String> nestedNames = new ArrayList<>();
                for (CommandLineParser<? extends CommandInvocation> nested : child.getAllChildParsers()) {
                    nestedNames.add(nested.getProcessedCommand().name().toLowerCase());
                }
                for (CommandLineParser<? extends CommandInvocation> nested : child.getAllChildParsers()) {
                    String nestedName = nested.getProcessedCommand().name().toLowerCase();
                    String nestedDesc = escapeFish(nested.getProcessedCommand().description());
                    out.append("complete -c ").append(programName).append(" -f")
                            .append(" -n \"__fish_seen_subcommand_from ").append(childName)
                            .append("; and not __fish_seen_subcommand_from ")
                            .append(String.join(" ", nestedNames)).append("\"")
                            .append(" -a ").append(nestedName);
                    if (!nestedDesc.isEmpty())
                        out.append(" -d '").append(nestedDesc).append("'");
                    out.append(NL);
                }
            }
            out.append(NL);
        }
    }

    private void generateSimpleCommand(StringBuilder out,
            CommandLineParser<? extends CommandInvocation> parser,
            String programName, String subcommand) {

        for (ProcessedOption option : parser.getProcessedCommand().getOptions()) {
            if (option.isProperty())
                continue;
            appendFishOption(out, programName, subcommand, option);
        }
    }

    private void appendFishOption(StringBuilder out, String programName,
            String subcommand, ProcessedOption option) {

        appendFishOptionEntry(out, programName, subcommand, option, option.name(), false);

        for (String alias : option.getAliases()) {
            appendFishOptionEntry(out, programName, subcommand, option, alias, false);
        }

        if (option.isNegatable() && option.getNegatedName() != null) {
            appendFishOptionEntry(out, programName, subcommand, option, option.getNegatedName(), true);
        }
    }

    private void appendFishOptionEntry(StringBuilder out, String programName,
            String subcommand, ProcessedOption option, String name, boolean isNegated) {

        boolean isFileOpt = option.isTypeAssignableByResourcesOrFile();

        out.append("complete -c ").append(programName);

        // Suppress file completion unless the option accepts file paths
        if (!isFileOpt)
            out.append(" -f");

        if (subcommand != null) {
            out.append(" -n \"__fish_seen_subcommand_from ").append(subcommand).append("\"");
        }

        out.append(" -l ").append(name);

        if (!isNegated && name.equals(option.name())
                && option.shortName() != null && !option.shortName().isEmpty()) {
            out.append(" -s ").append(option.shortName());
        }

        if (option.hasValue() && !isNegated)
            out.append(" -r");

        String desc = escapeFish(option.description());
        if (isNegated)
            desc = "Disable " + option.name();
        if (!desc.isEmpty())
            out.append(" -d '").append(desc).append("'");

        if (option.hasValue() && !isNegated && !isFileOpt) {
            List<String> vals = new ArrayList<>();
            if (option.hasDefaultValue())
                vals.addAll(option.getDefaultValues());
            if (BashCompletionGenerator.isBooleanType(option)) {
                vals.add("true");
                vals.add("false");
            }
            if (!vals.isEmpty())
                out.append(" -a '").append(String.join(" ", vals)).append("'");
        }

        out.append(NL);
    }

    @Override
    public String generateDynamic(CommandLineParser<? extends CommandInvocation> parser, String programName) {
        return "# Dynamic fish completion for " + programName + " — generated by Aesh." + NL +
                "# Place this file in ~/.config/fish/completions/" + programName + ".fish" + NL +
                NL +
                "complete -c " + programName + " -f -a '(" + NL +
                "    commandline -cop | read -la tokens" + NL +
                "    " + programName + " --aesh-complete -- $tokens[2..]" + NL +
                ")'" + NL;
    }

    private static String escapeFish(String s) {
        if (s == null || s.isEmpty())
            return "";
        return s.replace("\\", "\\\\").replace("'", "\\'");
    }
}
