/*
 * JBoss, Home of Professional Open Source
 * Copyright 2014 Red Hat Inc. and/or its affiliates and other contributors
 * as indicated by the @authors tag. All rights reserved.
 * See the copyright.txt in the distribution for a
 * full listing of individual contributors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * http://www.apache.org/licenses/LICENSE-2.0
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.aesh.util.completer;

import java.util.ArrayList;
import java.util.List;

import org.aesh.command.impl.internal.ProcessedCommand;
import org.aesh.command.impl.internal.ProcessedOption;
import org.aesh.command.impl.parser.CommandLineParser;
import org.aesh.command.invocation.CommandInvocation;

/**
 * Generates PowerShell completion scripts using Register-ArgumentCompleter.
 * <p>
 * Supports both static (hardcoded candidates) and dynamic (callback via
 * {@code --aesh-complete}) completion modes. Compatible with PowerShell 5.1+
 * (Windows PowerShell) and PowerShell 7+ (cross-platform).
 *
 * @author Aesh team
 */
class PowerShellCompletionGenerator implements ShellCompletionGenerator {

    private static final String NL = "\n";

    @Override
    public String generate(CommandLineParser<? extends CommandInvocation> parser, String programName) {
        StringBuilder out = new StringBuilder();
        out.append("# PowerShell completion for ").append(programName).append(" \u2014 generated by Aesh.").append(NL);
        out.append("# Add this to your $PROFILE or source it: . ").append(programName).append("_complete.ps1").append(NL);
        out.append(NL);

        out.append("Register-ArgumentCompleter -Native -CommandName '")
                .append(escapePwsh(programName)).append("'");
        out.append(" -ScriptBlock {").append(NL);
        out.append("    param($wordToComplete, $commandAst, $cursorPosition)").append(NL);
        out.append(NL);

        // Build static candidate lists
        if (parser.isGroupCommand()) {
            generateGroupCompletion(out, parser, programName);
        } else {
            generateSimpleCompletion(out, parser, programName, null);
        }

        out.append("}").append(NL);
        return out.toString();
    }

    private void generateSimpleCompletion(StringBuilder out,
            CommandLineParser<? extends CommandInvocation> parser, String programName,
            String parentName) {

        out.append("    $candidates = @()").append(NL);

        ProcessedCommand<?, ?> cmd = parser.getProcessedCommand();
        appendOptionCompletions(out, cmd, programName, parentName, "    ");

        // Arguments
        if (cmd.hasArgument() || cmd.hasArguments()) {
            ProcessedOption arg = cmd.hasArguments() ? cmd.getArguments() : cmd.getArgument();
            if (arg.isTypeAssignableByResourcesOrFile()) {
                out.append("    # File argument completion").append(NL);
                out.append("    if (-not $wordToComplete.StartsWith('-')) {").append(NL);
                out.append("        Get-ChildItem -Path \"$wordToComplete*\" -ErrorAction SilentlyContinue |").append(NL);
                out.append("            ForEach-Object { $candidates += [System.Management.Automation.CompletionResult]::new(");
                out.append("$_.Name, $_.Name, 'ProviderItem', $_.FullName) }").append(NL);
                out.append("    }").append(NL);
            } else if (arg.hasAllowedValues() || arg.hasDefaultValue()) {
                List<String> vals = new ArrayList<>();
                if (arg.hasAllowedValues())
                    vals.addAll(arg.getAllowedValues());
                else
                    vals.addAll(arg.getDefaultValues());
                for (String v : vals) {
                    appendCandidate(out, v, v, "    ");
                }
            }
        }

        out.append("    $candidates").append(NL);
    }

    private void generateGroupCompletion(StringBuilder out,
            CommandLineParser<? extends CommandInvocation> parser, String programName) {

        out.append("    $elems = $commandAst.CommandElements").append(NL);
        out.append("    $candidates = @()").append(NL);
        out.append(NL);

        // Subcommands at position 1
        out.append("    if ($elems.Count -le 1 -or ($elems.Count -eq 2 -and -not $commandAst.ToString().EndsWith(' '))) {")
                .append(NL);

        // Also offer root-level options
        appendOptionCompletions(out, parser.getProcessedCommand(), programName, null, "        ");

        for (CommandLineParser<? extends CommandInvocation> child : parser.getAllChildParsers()) {
            String name = child.getProcessedCommand().name();
            String desc = escapePwsh(ProcessedCommand.resolveDescription(
                    child.getProcessedCommand(), child.getProcessedCommand().description(),
                    programName, programName));
            appendCandidate(out, name, desc, "        ");
        }
        out.append("    } else {").append(NL);

        // Options for each subcommand
        out.append("        $sub = $elems[1].ToString()").append(NL);
        out.append("        switch ($sub) {").append(NL);
        for (CommandLineParser<? extends CommandInvocation> child : parser.getAllChildParsers()) {
            String childName = child.getProcessedCommand().name();
            out.append("            '").append(escapePwsh(childName)).append("' {").append(NL);
            appendOptionCompletions(out, child.getProcessedCommand(),
                    programName, programName, "                ");

            // Child arguments
            ProcessedCommand<?, ?> childCmd = child.getProcessedCommand();
            if (childCmd.hasArgument() || childCmd.hasArguments()) {
                ProcessedOption arg = childCmd.hasArguments() ? childCmd.getArguments() : childCmd.getArgument();
                if (arg.isTypeAssignableByResourcesOrFile()) {
                    out.append("                # File argument completion").append(NL);
                    out.append("                if (-not $wordToComplete.StartsWith('-')) {").append(NL);
                    out.append("                    Get-ChildItem -Path \"$wordToComplete*\" -ErrorAction SilentlyContinue |")
                            .append(NL);
                    out.append(
                            "                        ForEach-Object { $candidates += [System.Management.Automation.CompletionResult]::new(");
                    out.append("$_.Name, $_.Name, 'ProviderItem', $_.FullName) }").append(NL);
                    out.append("                }").append(NL);
                }
            }

            out.append("            }").append(NL);
        }
        out.append("        }").append(NL);
        out.append("    }").append(NL);
        out.append("    $candidates").append(NL);
    }

    /**
     * Emit completion candidates for all options on the given command.
     * Handles property filtering, aliases, short names, negatable options,
     * and value completion.
     */
    private void appendOptionCompletions(StringBuilder out, ProcessedCommand<?, ?> cmd,
            String programName, String parentName, String indent) {
        for (ProcessedOption opt : cmd.getOptions()) {
            if (opt.isProperty())
                continue;

            String desc = escapePwsh(ProcessedCommand.resolveOptionDesc(cmd, opt, programName, parentName));
            if (desc.isEmpty())
                desc = opt.name();

            // Primary long name
            String longName = "--" + opt.name();
            appendCandidate(out, longName, desc, indent);

            // Short name
            if (opt.shortName() != null && !opt.shortName().isEmpty()) {
                String shortName = "-" + opt.shortName();
                appendCandidate(out, shortName, desc, indent);
            }

            // Aliases
            for (String alias : opt.getAliases()) {
                appendCandidate(out, "--" + alias, desc, indent);
            }

            // Negatable
            if (opt.isNegatable() && opt.getNegatedName() != null) {
                appendCandidate(out, "--" + opt.getNegatedName(), "Disable " + opt.name(), indent);
            }
        }
    }

    /**
     * Emit a single CompletionResult candidate with -like filtering.
     */
    private void appendCandidate(StringBuilder out, String name, String desc, String indent) {
        out.append(indent).append("if ('").append(escapePwsh(name))
                .append("' -like \"$wordToComplete*\") {").append(NL);
        out.append(indent).append("    $candidates += [System.Management.Automation.CompletionResult]::new(");
        out.append("'").append(escapePwsh(name)).append("', '").append(escapePwsh(name))
                .append("', 'ParameterValue', '").append(escapePwsh(desc)).append("')");
        out.append(NL).append(indent).append("}").append(NL);
    }

    @Override
    public String generateDynamic(CommandLineParser<? extends CommandInvocation> parser, String programName) {
        String escaped = escapePwsh(programName);
        return "# Dynamic PowerShell completion for " + programName + " \u2014 generated by Aesh." + NL +
                "# Add this to your $PROFILE or source it: . " + programName + "_complete.ps1" + NL +
                NL +
                "Register-ArgumentCompleter -Native -CommandName '" + escaped + "' -ScriptBlock {" + NL +
                "    param($wordToComplete, $commandAst, $cursorPosition)" + NL +
                NL +
                "    $elems = $commandAst.CommandElements" + NL +
                "    $cmdArgs = @()" + NL +
                "    for ($i = 1; $i -lt $elems.Count; $i++) {" + NL +
                "        $cmdArgs += $elems[$i].ToString()" + NL +
                "    }" + NL +
                NL +
                "    # Detect trailing space for subcommand context" + NL +
                "    if ($commandAst.ToString().EndsWith(' ')) {" + NL +
                "        $cmdArgs += ''" + NL +
                "    }" + NL +
                NL +
                "    & '" + escaped + "' --aesh-complete -- @cmdArgs 2>$null | ForEach-Object {" + NL +
                "        $parts = $_ -split \"`t\", 2" + NL +
                "        $text = $parts[0].Trim()" + NL +
                "        if ($text -eq '__aesh_file__') {" + NL +
                "            Get-ChildItem -Path \"$wordToComplete*\" -ErrorAction SilentlyContinue |" + NL +
                "                ForEach-Object {" + NL +
                "                    [System.Management.Automation.CompletionResult]::new(" + NL +
                "                        $_.Name, $_.Name, 'ProviderItem', $_.FullName)" + NL +
                "                }" + NL +
                "        } elseif ($text -eq '__aesh_dir__') {" + NL +
                "            Get-ChildItem -Path \"$wordToComplete*\" -Directory -ErrorAction SilentlyContinue |" + NL +
                "                ForEach-Object {" + NL +
                "                    [System.Management.Automation.CompletionResult]::new(" + NL +
                "                        $_.Name, $_.Name, 'ProviderContainer', $_.FullName)" + NL +
                "                }" + NL +
                "        } elseif ($text) {" + NL +
                "            $desc = if ($parts.Length -gt 1) { $parts[1] } else { $text }" + NL +
                "            [System.Management.Automation.CompletionResult]::new(" + NL +
                "                $text, $text, 'ParameterValue', $desc)" + NL +
                "        }" + NL +
                "    }" + NL +
                "}" + NL;
    }

    private static String escapePwsh(String s) {
        if (s == null || s.isEmpty())
            return "";
        return s.replace("'", "''");
    }
}
