/*
 * JBoss, Home of Professional Open Source
 * Copyright 2014 Red Hat Inc. and/or its affiliates and other contributors
 * as indicated by the @authors tag. All rights reserved.
 * See the copyright.txt in the distribution for a
 * full listing of individual contributors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * http://www.apache.org/licenses/LICENSE-2.0
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.aesh.util.completer;

import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import org.aesh.command.impl.internal.ProcessedCommand;
import org.aesh.command.impl.internal.ProcessedOption;
import org.aesh.command.impl.parser.CommandLineParser;
import org.aesh.command.invocation.CommandInvocation;

/**
 * Generates PowerShell completion scripts using Register-ArgumentCompleter.
 * <p>
 * Supports both static (hardcoded candidates) and dynamic (callback via
 * {@code --aesh-complete}) completion modes. Compatible with PowerShell 5.1+
 * (Windows PowerShell) and PowerShell 7+ (cross-platform).
 *
 * @author Aesh team
 */
class PowerShellCompletionGenerator implements ShellCompletionGenerator {

    private static final String NL = "\n";

    @Override
    public String generate(CommandLineParser<? extends CommandInvocation> parser, String programName) {
        return generate(parser, programName, CompletionFilter.defaults());
    }

    @Override
    public String generate(CommandLineParser<? extends CommandInvocation> parser, String programName,
            CompletionFilter filter) {
        StringBuilder out = new StringBuilder();
        out.append("# PowerShell completion for ").append(programName).append(" \u2014 generated by Aesh.").append(NL);
        out.append("# Add this to your $PROFILE or source it: . ").append(programName).append("_complete.ps1").append(NL);
        out.append(NL);

        out.append("Register-ArgumentCompleter -Native -CommandName '")
                .append(escapePwsh(programName)).append("'");
        out.append(" -ScriptBlock {").append(NL);
        out.append("    param($wordToComplete, $commandAst, $cursorPosition)").append(NL);
        out.append(NL);

        // Build static candidate lists
        if (parser.isGroupCommand()) {
            generateGroupCompletion(out, parser, programName, filter);
        } else {
            generateSimpleCompletion(out, parser, programName, null, filter);
        }

        out.append("}").append(NL);
        return out.toString();
    }

    private void generateSimpleCompletion(StringBuilder out,
            CommandLineParser<? extends CommandInvocation> parser, String programName,
            String parentName, CompletionFilter filter) {

        out.append("    $candidates = @()").append(NL);

        ProcessedCommand<?, ?> cmd = parser.getProcessedCommand();
        emitValueCheck(out, mergedOptions(parser,
                Collections.<CommandLineParser<? extends CommandInvocation>> emptyList(), filter),
                cmd, programName, parentName, "    ");
        appendOptionCompletions(out, mergedOptions(parser,
                Collections.<CommandLineParser<? extends CommandInvocation>> emptyList(), filter),
                cmd, programName, parentName, "    ", filter);

        // Arguments
        if (cmd.hasArgument() || cmd.hasArguments()) {
            ProcessedOption arg = cmd.hasArguments() ? cmd.getArguments() : cmd.getArgument();
            if (!filter.includeOption(cmd, arg)) {
                out.append("    $candidates").append(NL);
                return;
            }
            if (arg.isTypeAssignableByResourcesOrFile()) {
                out.append("    # File argument completion").append(NL);
                out.append("    if (-not $wordToComplete.StartsWith('-')) {").append(NL);
                out.append("        Get-ChildItem -Path \"$wordToComplete*\" -ErrorAction SilentlyContinue |").append(NL);
                out.append("            ForEach-Object { $candidates += [System.Management.Automation.CompletionResult]::new(");
                out.append("$_.Name, $_.Name, 'ProviderItem', $_.FullName) }").append(NL);
                out.append("    }").append(NL);
            } else if (arg.hasAllowedValues() || arg.hasDefaultValue()) {
                List<String> vals = new ArrayList<>();
                if (arg.hasAllowedValues())
                    vals.addAll(arg.getAllowedValues());
                else
                    vals.addAll(arg.getDefaultValues());
                for (String v : vals) {
                    appendCandidate(out, v, v, "    ");
                }
            }
        }

        out.append("    $candidates").append(NL);
    }

    private void generateGroupCompletion(StringBuilder out,
            CommandLineParser<? extends CommandInvocation> parser, String programName,
            CompletionFilter filter) {

        out.append("    $elems = $commandAst.CommandElements").append(NL);
        out.append("    $candidates = @()").append(NL);
        out.append(NL);

        // Detect trailing space: cursor is past the end of the AST text.
        // $commandAst.ToString() strips trailing whitespace, so EndsWith(' ')
        // does not work reliably (#544). Use cursorPosition instead.
        out.append("    $isTrailing = $cursorPosition -gt $commandAst.ToString().Length").append(NL);
        out.append(NL);

        generateLevel(out, parser, programName, 1,
                Collections.<CommandLineParser<? extends CommandInvocation>> emptyList(), filter,
                "    ");
        out.append("    $candidates").append(NL);
    }

    /**
     * Emits completion for one group level. {@code depth} is the
     * {@code $elems} index of the word selecting among this parser's children
     * (1 for the root). The first prior word naming a child wins and control
     * descends; otherwise the level offers its own options (plus inherited
     * ones, nearest first) and its children's names (#671).
     */
    private void generateLevel(StringBuilder out,
            CommandLineParser<? extends CommandInvocation> parser, String programName, int depth,
            List<CommandLineParser<? extends CommandInvocation>> ancestors,
            CompletionFilter filter, String indent) {
        String subVar = depth == 1 ? "$sub" : "$sub" + depth;
        String endVar = depth == 1 ? "$end" : "$end" + depth;
        String idxVar = depth == 1 ? "$i" : "$i" + depth;

        out.append(indent).append(subVar).append(" = \"\"").append(NL);
        out.append(indent).append(endVar).append(" = $elems.Count - 1").append(NL);
        out.append(indent).append("if (-not $isTrailing) { ").append(endVar).append("-- }").append(NL);
        out.append(indent).append("for (").append(idxVar).append(" = ").append(depth).append("; ")
                .append(idxVar).append(" -le ").append(endVar).append("; ").append(idxVar).append("++) {")
                .append(NL);
        out.append(indent).append("    if (").append(subVar).append(" -eq \"\" -and @(");
        boolean first = true;
        for (CommandLineParser<? extends CommandInvocation> child : CompletionFilter.visibleChildren(parser,
                filter)) {
            if (!first)
                out.append(", ");
            out.append("'").append(escapePwsh(child.getProcessedCommand().name())).append("'");
            first = false;
        }
        out.append(") -contains $elems[").append(idxVar).append("].ToString()) {").append(NL);
        out.append(indent).append("        ").append(subVar).append(" = $elems[").append(idxVar)
                .append("].ToString()").append(NL);
        out.append(indent).append("    }").append(NL);
        out.append(indent).append("}").append(NL);

        out.append(indent).append("if (").append(subVar).append(" -eq \"\") {").append(NL);
        List<ProcessedOption> options = mergedOptions(parser, ancestors, filter);
        ProcessedCommand<?, ?> cmd = parser.getProcessedCommand();
        String parentName = ancestors.isEmpty() ? null : ancestors.get(0).getProcessedCommand().name();
        emitValueCheck(out, options, cmd, programName, parentName, indent + "    ");
        appendOptionCompletions(out, options, cmd, programName, parentName, indent + "    ", filter);

        for (CommandLineParser<? extends CommandInvocation> child : CompletionFilter.visibleChildren(parser,
                filter)) {
            String name = child.getProcessedCommand().name();
            String desc = escapePwsh(ProcessedCommand.resolveDescription(
                    child.getProcessedCommand(), child.getProcessedCommand().description(),
                    programName, ancestors.isEmpty() ? programName : cmd.name()));
            appendCandidate(out, name, desc, indent + "    ");
        }
        emitFileArgumentCompletion(out, cmd, filter, indent + "    ");

        out.append(indent).append("} else {").append(NL);
        out.append(indent).append("    switch (").append(subVar).append(") {").append(NL);
        for (CommandLineParser<? extends CommandInvocation> child : CompletionFilter.visibleChildren(parser,
                filter)) {
            String childName = child.getProcessedCommand().name();
            out.append(indent).append("        '").append(escapePwsh(childName)).append("' {").append(NL);
            List<CommandLineParser<? extends CommandInvocation>> childAncestors = new ArrayList<>(
                    ancestors);
            childAncestors.add(0, parser);
            if (child.isGroupCommand()) {
                generateLevel(out, child, programName, depth + 1, childAncestors, filter,
                        indent + "            ");
            } else {
                ProcessedCommand<?, ?> childCmd = child.getProcessedCommand();
                String childParentName = ancestors.isEmpty() ? programName : cmd.name();
                List<ProcessedOption> childOptions = mergedOptions(child, childAncestors, filter);
                emitValueCheck(out, childOptions, childCmd, programName, childParentName,
                        indent + "            ");
                appendOptionCompletions(out, childOptions, childCmd, programName, childParentName,
                        indent + "            ", filter);
                emitFileArgumentCompletion(out, childCmd, filter, indent + "            ");
            }
            out.append(indent).append("        }").append(NL);
        }
        out.append(indent).append("    }").append(NL);
        out.append(indent).append("}").append(NL);
    }

    /**
     * Own options plus inherited options from ancestors (nearest first),
     * mirroring the dynamic completion path and the bash/zsh generators. A
     * redefined name on the child wins over the inherited one.
     */
    private static List<ProcessedOption> mergedOptions(
            CommandLineParser<? extends CommandInvocation> parser,
            List<CommandLineParser<? extends CommandInvocation>> ancestors,
            CompletionFilter filter) {
        List<ProcessedOption> options = new ArrayList<>(
                CompletionFilter.visibleOptions(parser.getProcessedCommand(), filter));
        Set<String> emittedNames = new HashSet<>();
        for (ProcessedOption option : options) {
            if (option.name() != null)
                emittedNames.add(option.name());
        }
        for (CommandLineParser<? extends CommandInvocation> ancestor : ancestors) {
            for (ProcessedOption option : CompletionFilter.visibleOptions(
                    ancestor.getProcessedCommand(), filter)) {
                if (option.isInherited() && option.name() != null
                        && emittedNames.add(option.name()))
                    options.add(option);
            }
        }
        return options;
    }

    /**
     * When the word before the current one takes a value, offer that option's
     * values exclusively, mirroring the dynamic completion path. Options
     * without known values fall through to the regular option listing.
     */
    private void emitValueCheck(StringBuilder out, List<ProcessedOption> options,
            ProcessedCommand<?, ?> cmd, String programName, String parentName, String indent) {
        List<ProcessedOption> valued = new ArrayList<>();
        for (ProcessedOption option : options) {
            if (!option.hasValue())
                continue;
            if (option.hasAllowedValues() || option.hasDefaultValue()
                    || option.isTypeAssignableByResourcesOrFile()
                    || BashCompletionGenerator.isBooleanType(option))
                valued.add(option);
        }
        if (valued.isEmpty())
            return;

        out.append(indent).append("$prev = \"\"").append(NL);
        out.append(indent).append("if ($isTrailing) {").append(NL);
        out.append(indent).append("    if ($elems.Count -ge 1) { $prev = $elems[$elems.Count - 1].ToString() }")
                .append(NL);
        out.append(indent).append("} elseif ($elems.Count -ge 2) {").append(NL);
        out.append(indent).append("    $prev = $elems[$elems.Count - 2].ToString()").append(NL);
        out.append(indent).append("}").append(NL);
        out.append(indent).append("switch ($prev) {").append(NL);
        for (ProcessedOption option : valued) {
            emitValueArm(out, option, cmd, programName, parentName, indent + "    ");
        }
        out.append(indent).append("}").append(NL);
    }

    private void emitValueArm(StringBuilder out, ProcessedOption option,
            ProcessedCommand<?, ?> cmd, String programName, String parentName, String indent) {
        List<String> forms = new ArrayList<>();
        forms.add("--" + option.name());
        if (option.shortName() != null && !option.shortName().isEmpty())
            forms.add("-" + option.shortName());
        for (String alias : option.getAliases())
            forms.add("--" + alias);
        for (String form : forms) {
            out.append(indent).append("'").append(escapePwsh(form)).append("' {").append(NL);
            if (option.isTypeAssignableByResourcesOrFile()) {
                out.append(indent).append("    if (-not $wordToComplete.StartsWith('-')) {").append(NL);
                out.append(indent).append("        Get-ChildItem -Path \"$wordToComplete*\" -ErrorAction SilentlyContinue |")
                        .append(NL);
                out.append(indent).append(
                        "            ForEach-Object { $candidates += [System.Management.Automation.CompletionResult]::new(");
                out.append("$_.Name, $_.Name, 'ProviderItem', $_.FullName) }").append(NL);
                out.append(indent).append("    }").append(NL);
            } else {
                List<String> vals = new ArrayList<>();
                if (option.hasAllowedValues())
                    vals.addAll(option.getAllowedValues());
                else
                    vals.addAll(option.getDefaultValues());
                if (BashCompletionGenerator.isBooleanType(option)) {
                    vals.add("true");
                    vals.add("false");
                }
                for (String v : vals) {
                    String desc = escapePwsh(ProcessedCommand.resolveOptionDesc(cmd, option, programName,
                            parentName));
                    if (desc.isEmpty())
                        desc = v;
                    appendCandidate(out, v, desc, indent + "    ");
                }
            }
            out.append(indent).append("    return $candidates").append(NL);
            out.append(indent).append("}").append(NL);
        }
    }

    private void emitFileArgumentCompletion(StringBuilder out, ProcessedCommand<?, ?> cmd,
            CompletionFilter filter, String indent) {
        if (!cmd.hasArgument() && !cmd.hasArguments())
            return;
        ProcessedOption arg = cmd.hasArguments() ? cmd.getArguments() : cmd.getArgument();
        if (!filter.includeOption(cmd, arg) || !arg.isTypeAssignableByResourcesOrFile())
            return;
        out.append(indent).append("# File argument completion").append(NL);
        out.append(indent).append("if (-not $wordToComplete.StartsWith('-')) {").append(NL);
        out.append(indent).append("    Get-ChildItem -Path \"$wordToComplete*\" -ErrorAction SilentlyContinue |")
                .append(NL);
        out.append(indent)
                .append("        ForEach-Object { $candidates += [System.Management.Automation.CompletionResult]::new(");
        out.append("$_.Name, $_.Name, 'ProviderItem', $_.FullName) }").append(NL);
        out.append(indent).append("}").append(NL);
    }

    /**
     * Emit completion candidates for all options on the given command.
     * Handles property filtering, aliases, short names, negatable options,
     * and value completion.
     */
    private void appendOptionCompletions(StringBuilder out, List<ProcessedOption> options,
            ProcessedCommand<?, ?> cmd,
            String programName, String parentName, String indent, CompletionFilter filter) {
        for (ProcessedOption opt : options) {
            String desc = escapePwsh(ProcessedCommand.resolveOptionDesc(cmd, opt, programName, parentName));
            if (desc.isEmpty())
                desc = opt.name();

            // Primary long name
            String longName = "--" + opt.name();
            appendCandidate(out, longName, desc, indent);

            // Short name
            if (opt.shortName() != null && !opt.shortName().isEmpty()) {
                String shortName = "-" + opt.shortName();
                appendCandidate(out, shortName, desc, indent);
            }

            // Aliases
            for (String alias : opt.getAliases()) {
                appendCandidate(out, "--" + alias, desc, indent);
            }

            // Negatable
            if (opt.isNegatable() && opt.getNegatedName() != null) {
                appendCandidate(out, "--" + opt.getNegatedName(), "Disable " + opt.name(), indent);
            }
        }
    }

    /**
     * Emit a single CompletionResult candidate with -like filtering.
     */
    private void appendCandidate(StringBuilder out, String name, String desc, String indent) {
        out.append(indent).append("if ('").append(escapePwsh(name))
                .append("' -like \"$wordToComplete*\") {").append(NL);
        out.append(indent).append("    $candidates += [System.Management.Automation.CompletionResult]::new(");
        out.append("'").append(escapePwsh(name)).append("', '").append(escapePwsh(name))
                .append("', 'ParameterValue', '").append(escapePwsh(desc)).append("')");
        out.append(NL).append(indent).append("}").append(NL);
    }

    @Override
    public String generateDynamic(CommandLineParser<? extends CommandInvocation> parser, String programName) {
        String escaped = escapePwsh(programName);
        return "# Dynamic PowerShell completion for " + programName + " \u2014 generated by Aesh." + NL +
                "# Add this to your $PROFILE or source it: . " + programName + "_complete.ps1" + NL +
                NL +
                "Register-ArgumentCompleter -Native -CommandName '" + escaped + "' -ScriptBlock {" + NL +
                "    param($wordToComplete, $commandAst, $cursorPosition)" + NL +
                NL +
                "    $elems = $commandAst.CommandElements" + NL +
                "    $cmdArgs = @()" + NL +
                "    for ($i = 1; $i -lt $elems.Count; $i++) {" + NL +
                "        $cmdArgs += $elems[$i].ToString()" + NL +
                "    }" + NL +
                NL +
                "    # Detect trailing space: cursor is past the end of the AST text." + NL +
                "    # $commandAst.ToString() strips trailing whitespace, so EndsWith(' ')" + NL +
                "    # does not work reliably (#544). Use cursorPosition instead." + NL +
                "    if ($cursorPosition -gt $commandAst.ToString().Length) {" + NL +
                "        $cmdArgs += ''" + NL +
                "    }" + NL +
                NL +
                "    & '" + escaped + "' --aesh-complete -- @cmdArgs 2>$null | ForEach-Object {" + NL +
                "        $parts = $_ -split \"`t\", 2" + NL +
                "        $text = $parts[0].Trim()" + NL +
                "        if ($text -eq '__aesh_file__') {" + NL +
                "            Get-ChildItem -Path \"$wordToComplete*\" -ErrorAction SilentlyContinue |" + NL +
                "                ForEach-Object {" + NL +
                "                    [System.Management.Automation.CompletionResult]::new(" + NL +
                "                        $_.Name, $_.Name, 'ProviderItem', $_.FullName)" + NL +
                "                }" + NL +
                "        } elseif ($text -eq '__aesh_dir__') {" + NL +
                "            Get-ChildItem -Path \"$wordToComplete*\" -Directory -ErrorAction SilentlyContinue |" + NL +
                "                ForEach-Object {" + NL +
                "                    [System.Management.Automation.CompletionResult]::new(" + NL +
                "                        $_.Name, $_.Name, 'ProviderContainer', $_.FullName)" + NL +
                "                }" + NL +
                "        } elseif ($text) {" + NL +
                "            $desc = if ($parts.Length -gt 1) { $parts[1] } else { $text }" + NL +
                "            [System.Management.Automation.CompletionResult]::new(" + NL +
                "                $text, $text, 'ParameterValue', $desc)" + NL +
                "        }" + NL +
                "    }" + NL +
                "}" + NL;
    }

    private static String escapePwsh(String s) {
        if (s == null || s.isEmpty())
            return "";
        return s.replace("'", "''");
    }
}
