/*
 * JBoss, Home of Professional Open Source
 * Copyright 2014 Red Hat Inc. and/or its affiliates and other contributors
 * as indicated by the @authors tag. All rights reserved.
 * See the copyright.txt in the distribution for a
 * full listing of individual contributors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * http://www.apache.org/licenses/LICENSE-2.0
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.aesh.util.completer;

import java.util.List;

import org.aesh.command.impl.internal.ProcessedCommand;
import org.aesh.command.impl.internal.ProcessedOption;
import org.aesh.command.impl.parser.CommandLineParser;
import org.aesh.command.invocation.CommandInvocation;

/**
 * Generates PowerShell completion scripts using Register-ArgumentCompleter.
 * <p>
 * Supports both static (hardcoded candidates) and dynamic (callback via
 * {@code --aesh-complete}) completion modes. Compatible with PowerShell 5.1+
 * (Windows PowerShell) and PowerShell 7+ (cross-platform).
 *
 * @author Aesh team
 */
class PowerShellCompletionGenerator implements ShellCompletionGenerator {

    private static final String NL = System.lineSeparator();

    @Override
    public String generate(CommandLineParser<? extends CommandInvocation> parser, String programName) {
        StringBuilder out = new StringBuilder();
        out.append("# PowerShell completion for ").append(programName).append(" \u2014 generated by Aesh.").append(NL);
        out.append("# Add this to your $PROFILE or source it: . ").append(programName).append("_complete.ps1").append(NL);
        out.append(NL);

        out.append("Register-ArgumentCompleter -Native -CommandName ").append(programName);
        out.append(" -ScriptBlock {").append(NL);
        out.append("    param($wordToComplete, $commandAst, $cursorPosition)").append(NL);
        out.append(NL);

        // Build static candidate lists
        if (parser.isGroupCommand()) {
            generateGroupCompletion(out, parser, programName);
        } else {
            generateSimpleCompletion(out, parser, programName, null);
        }

        out.append("}").append(NL);
        return out.toString();
    }

    private void generateSimpleCompletion(StringBuilder out,
            CommandLineParser<? extends CommandInvocation> parser, String programName,
            String parentName) {

        out.append("    $candidates = @()").append(NL);

        // Options
        ProcessedCommand<?, ?> cmd = parser.getProcessedCommand();
        List<ProcessedOption> options = cmd.getOptions();
        for (ProcessedOption opt : options) {
            String name = opt.name() != null && !opt.name().isEmpty() ? "--" + opt.name() : "-" + opt.shortName();
            String desc = escapePwsh(ProcessedCommand.resolveOptionDesc(cmd, opt, programName, parentName));
            out.append("    if ('").append(name).append("' -like \"$wordToComplete*\") {").append(NL);
            out.append("        $candidates += [System.Management.Automation.CompletionResult]::new(");
            out.append("'").append(name).append("', '").append(name).append("', 'ParameterValue', '").append(desc).append("')");
            out.append(NL).append("    }").append(NL);
        }

        out.append("    $candidates").append(NL);
    }

    private void generateGroupCompletion(StringBuilder out,
            CommandLineParser<? extends CommandInvocation> parser, String programName) {

        out.append("    $tokens = $commandAst.ToString().Split(' ', [StringSplitOptions]::RemoveEmptyEntries)").append(NL);
        out.append("    $candidates = @()").append(NL);
        out.append(NL);

        // Subcommands at position 1
        out.append("    if ($tokens.Length -le 1 -or ($tokens.Length -eq 2 -and -not $commandAst.ToString().EndsWith(' '))) {")
                .append(NL);
        for (CommandLineParser<? extends CommandInvocation> child : parser.getAllChildParsers()) {
            String name = child.getProcessedCommand().name();
            String desc = escapePwsh(ProcessedCommand.resolveDescription(
                    child.getProcessedCommand(), child.getProcessedCommand().description(),
                    programName, programName));
            out.append("        if ('").append(name).append("' -like \"$wordToComplete*\") {").append(NL);
            out.append("            $candidates += [System.Management.Automation.CompletionResult]::new(");
            out.append("'").append(name).append("', '").append(name).append("', 'ParameterValue', '").append(desc).append("')");
            out.append(NL).append("        }").append(NL);
        }
        out.append("    } else {").append(NL);

        // Options for each subcommand
        out.append("        $sub = $tokens[1]").append(NL);
        out.append("        switch ($sub) {").append(NL);
        for (CommandLineParser<? extends CommandInvocation> child : parser.getAllChildParsers()) {
            String childName = child.getProcessedCommand().name();
            out.append("            '").append(childName).append("' {").append(NL);
            for (ProcessedOption opt : child.getProcessedCommand().getOptions()) {
                String optName = opt.name() != null && !opt.name().isEmpty() ? "--" + opt.name() : "-" + opt.shortName();
                String desc = escapePwsh(ProcessedCommand.resolveOptionDesc(
                        child.getProcessedCommand(), opt, programName, programName));
                out.append("                if ('").append(optName).append("' -like \"$wordToComplete*\") {").append(NL);
                out.append("                    $candidates += [System.Management.Automation.CompletionResult]::new(");
                out.append("'").append(optName).append("', '").append(optName).append("', 'ParameterValue', '").append(desc)
                        .append("')");
                out.append(NL).append("                }").append(NL);
            }
            out.append("            }").append(NL);
        }
        out.append("        }").append(NL);
        out.append("    }").append(NL);
        out.append("    $candidates").append(NL);
    }

    @Override
    public String generateDynamic(CommandLineParser<? extends CommandInvocation> parser, String programName) {
        return "# Dynamic PowerShell completion for " + programName + " \u2014 generated by Aesh." + NL +
                "# Add this to your $PROFILE or source it: . " + programName + "_complete.ps1" + NL +
                NL +
                "Register-ArgumentCompleter -Native -CommandName " + programName + " -ScriptBlock {" + NL +
                "    param($wordToComplete, $commandAst, $cursorPosition)" + NL +
                NL +
                "    $tokens = $commandAst.ToString().Split(' ', [StringSplitOptions]::RemoveEmptyEntries)" + NL +
                "    $cmdArgs = if ($tokens.Length -gt 1) { $tokens[1..($tokens.Length - 1)] } else { @() }" + NL +
                NL +
                "    # Detect trailing space for subcommand context" + NL +
                "    if ($commandAst.ToString().EndsWith(' ')) {" + NL +
                "        $cmdArgs += ''" + NL +
                "    }" + NL +
                NL +
                "    & " + programName + " --aesh-complete -- @cmdArgs 2>$null | ForEach-Object {" + NL +
                "        $parts = $_ -split \"`t\", 2" + NL +
                "        $text = $parts[0].Trim()" + NL +
                "        if ($text -eq '__aesh_file__') {" + NL +
                "            Get-ChildItem -Path \"$wordToComplete*\" -ErrorAction SilentlyContinue |" + NL +
                "                ForEach-Object {" + NL +
                "                    [System.Management.Automation.CompletionResult]::new(" + NL +
                "                        $_.Name, $_.Name, 'ProviderItem', $_.FullName)" + NL +
                "                }" + NL +
                "        } elseif ($text -eq '__aesh_dir__') {" + NL +
                "            Get-ChildItem -Path \"$wordToComplete*\" -Directory -ErrorAction SilentlyContinue |" + NL +
                "                ForEach-Object {" + NL +
                "                    [System.Management.Automation.CompletionResult]::new(" + NL +
                "                        $_.Name, $_.Name, 'ProviderContainer', $_.FullName)" + NL +
                "                }" + NL +
                "        } elseif ($text) {" + NL +
                "            $desc = if ($parts.Length -gt 1) { $parts[1] } else { $text }" + NL +
                "            [System.Management.Automation.CompletionResult]::new(" + NL +
                "                $text, $text, 'ParameterValue', $desc)" + NL +
                "        }" + NL +
                "    }" + NL +
                "}" + NL;
    }

    private static String escapePwsh(String s) {
        if (s == null || s.isEmpty())
            return "";
        return s.replace("'", "''");
    }
}
