/*
 * JBoss, Home of Professional Open Source
 * Copyright 2014 Red Hat Inc. and/or its affiliates and other contributors
 * as indicated by the @authors tag
 * See the copyright.txt in the distribution for a
 * full listing of individual contributors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.aesh.util.completer;

import org.aesh.command.impl.internal.ProcessedCommand;
import org.aesh.command.impl.internal.ProcessedOption;
import org.aesh.command.impl.parser.CommandLineParser;
import org.aesh.command.invocation.CommandInvocation;

/**
 * Generates native zsh completion scripts using compdef/_arguments.
 *
 * @author Aesh team
 */
public class ZshCompletionGenerator implements ShellCompletionGenerator {

    private static final String NL = "\n";

    @Override
    public String generate(CommandLineParser<? extends CommandInvocation> parser, String programName) {
        StringBuilder out = new StringBuilder();
        out.append("#compdef ").append(programName).append(NL);
        out.append(NL);
        out.append("# Zsh completion for ").append(programName).append(" — generated by Aesh.").append(NL);
        out.append("# Place this file in a directory listed in $fpath (e.g., ~/.zsh/completions/)").append(NL);
        out.append(NL);

        generateFunction(out, parser, programName, "_" + programName, null);
        if (parser.isGroupCommand()) {
            for (CommandLineParser<? extends CommandInvocation> child : parser.getAllChildParsers()) {
                String childFuncName = "_" + programName + "_" + child.getProcessedCommand().name().toLowerCase();
                generateFunction(out, child, programName, childFuncName, programName);
            }
        }

        out.append("_").append(programName).append(" \"$@\"").append(NL);

        return out.toString();
    }

    private void generateFunction(StringBuilder out,
            CommandLineParser<? extends CommandInvocation> parser,
            String programName, String funcName, String parentName) {
        out.append(funcName).append("() {").append(NL);

        if (parser.isGroupCommand()) {
            generateGroupCommandBody(out, parser, programName);
        } else {
            generateSimpleCommandBody(out, parser, programName, parentName);
        }

        out.append("}").append(NL).append(NL);
    }

    private void generateGroupCommandBody(StringBuilder out,
            CommandLineParser<? extends CommandInvocation> parser,
            String programName) {
        out.append("    local -a commands").append(NL);
        out.append("    commands=(").append(NL);
        for (CommandLineParser<? extends CommandInvocation> child : parser.getAllChildParsers()) {
            String name = child.getProcessedCommand().name().toLowerCase();
            String desc = escapeZsh(ProcessedCommand.resolveDescription(
                    child.getProcessedCommand(), child.getProcessedCommand().description(),
                    programName, programName));
            if (desc.isEmpty())
                desc = name;
            out.append("        '").append(name).append(":").append(desc).append("'").append(NL);
        }
        out.append("    )").append(NL);
        out.append(NL);

        out.append("    _arguments -C \\").append(NL);
        appendOptionsAsArguments(out, parser, programName, null);
        out.append("        '1:command:->cmd' \\").append(NL);
        out.append("        '*::arg:->args'").append(NL);
        out.append(NL);

        out.append("    case $state in").append(NL);
        out.append("        cmd)").append(NL);
        out.append("            _describe 'command' commands").append(NL);
        out.append("            ;;").append(NL);
        out.append("        args)").append(NL);
        out.append("            case ${words[1]} in").append(NL);
        for (CommandLineParser<? extends CommandInvocation> child : parser.getAllChildParsers()) {
            String childName = child.getProcessedCommand().name().toLowerCase();
            out.append("                ").append(childName).append(")").append(NL);
            out.append("                    _").append(programName).append("_")
                    .append(childName).append(NL);
            out.append("                    ;;").append(NL);
        }
        out.append("            esac").append(NL);
        out.append("            ;;").append(NL);
        out.append("    esac").append(NL);
    }

    private void generateSimpleCommandBody(StringBuilder out,
            CommandLineParser<? extends CommandInvocation> parser,
            String programName, String parentName) {
        out.append("    _arguments \\").append(NL);
        appendOptionsAsArguments(out, parser, programName, parentName);

        if (parser.getProcessedCommand().hasArguments() || parser.getProcessedCommand().hasArgument()) {
            ProcessedOption arg = parser.getProcessedCommand().hasArguments()
                    ? parser.getProcessedCommand().getArguments()
                    : parser.getProcessedCommand().getArgument();
            String desc = escapeZsh(ProcessedCommand.resolveOptionDesc(
                    parser.getProcessedCommand(), arg, programName, parentName));
            if (desc.isEmpty())
                desc = "argument";

            if (arg.isTypeAssignableByResourcesOrFile()) {
                out.append("        '*:").append(desc).append(":_files'").append(NL);
            } else if (arg.hasDefaultValue()) {
                StringBuilder vals = new StringBuilder();
                for (String v : arg.getDefaultValues())
                    vals.append(v).append(" ");
                out.append("        '*:").append(desc).append(":(").append(vals.toString().trim())
                        .append(")'").append(NL);
            } else {
                out.append("        '*:").append(desc).append(":'").append(NL);
            }
        }
    }

    private void appendOptionsAsArguments(StringBuilder out,
            CommandLineParser<? extends CommandInvocation> parser,
            String programName, String parentName) {
        for (ProcessedOption option : parser.getProcessedCommand().getOptions()) {
            if (option.isProperty())
                continue;

            appendZshOption(out, option, parser.getProcessedCommand(), programName, parentName);

            for (String alias : option.getAliases()) {
                appendZshOptionAlias(out, option, parser.getProcessedCommand(), programName, parentName, alias);
            }

            if (option.isNegatable() && option.getNegatedName() != null) {
                out.append("        '--").append(option.getNegatedName())
                        .append("[Disable ").append(escapeZsh(option.name())).append("]' \\").append(NL);
            }
        }
    }

    private void appendZshOption(StringBuilder out, ProcessedOption option,
            ProcessedCommand<?, ?> cmd, String programName, String parentName) {
        StringBuilder spec = new StringBuilder();
        spec.append("'");

        if (option.shortName() != null && !option.shortName().isEmpty()) {
            spec.append("(-").append(option.shortName()).append(")");
        }
        spec.append("--").append(option.name());

        String desc = escapeZsh(ProcessedCommand.resolveOptionDesc(cmd, option, programName, parentName));
        spec.append("[").append(desc.isEmpty() ? option.name() : desc).append("]");

        appendValueSpec(spec, option, cmd, programName, parentName);
        spec.append("' \\");
        out.append("        ").append(spec).append(NL);

        if (option.shortName() != null && !option.shortName().isEmpty()) {
            StringBuilder shortSpec = new StringBuilder();
            shortSpec.append("'(--").append(option.name()).append(")");
            shortSpec.append("-").append(option.shortName());
            shortSpec.append("[").append(desc.isEmpty() ? option.name() : desc).append("]");
            appendValueSpec(shortSpec, option, cmd, programName, parentName);
            shortSpec.append("' \\");
            out.append("        ").append(shortSpec).append(NL);
        }
    }

    private void appendZshOptionAlias(StringBuilder out, ProcessedOption option,
            ProcessedCommand<?, ?> cmd, String programName, String parentName, String alias) {
        StringBuilder spec = new StringBuilder();
        spec.append("'(--").append(option.name()).append(")");
        spec.append("--").append(alias);

        String desc = escapeZsh(ProcessedCommand.resolveOptionDesc(cmd, option, programName, parentName));
        spec.append("[").append(desc.isEmpty() ? option.name() : desc).append("]");

        appendValueSpec(spec, option, cmd, programName, parentName);
        spec.append("' \\");
        out.append("        ").append(spec).append(NL);
    }

    private void appendValueSpec(StringBuilder spec, ProcessedOption option,
            ProcessedCommand<?, ?> cmd, String programName, String parentName) {
        if (!option.hasValue())
            return;

        String resolved = ProcessedCommand.resolveOptionDesc(cmd, option, programName, parentName);
        String desc = (resolved == null || resolved.isEmpty()) ? "value" : escapeZsh(resolved);

        if (option.isTypeAssignableByResourcesOrFile()) {
            spec.append(":").append(desc).append(":_files");
        } else if (option.hasAllowedValues() || option.hasDefaultValue()) {
            StringBuilder vals = new StringBuilder();
            vals.append("(");
            if (option.hasAllowedValues())
                for (String v : option.getAllowedValues())
                    vals.append(v).append(" ");
            else
                for (String v : option.getDefaultValues())
                    vals.append(v).append(" ");
            if (BashCompletionGenerator.isBooleanType(option))
                vals.append("true false ");
            vals.append(")");
            spec.append(":").append(desc).append(":").append(vals.toString().trim());
        } else if (BashCompletionGenerator.isBooleanType(option)) {
            spec.append(":").append(desc).append(":(true false)");
        } else {
            spec.append(":").append(desc).append(":");
        }
    }

    @Override
    public String generateDynamic(CommandLineParser<? extends CommandInvocation> parser, String programName) {
        return "#compdef " + programName + NL +
                NL +
                "# Dynamic zsh completion for " + programName + " — generated by Aesh." + NL +
                "# Place this file in a directory listed in $fpath (e.g., ~/.zsh/completions/)" + NL +
                NL +
                "_" + programName + "() {" + NL +
                "    local -a completions descriptions" + NL +
                "    local line has_file_sentinel=0 has_dir_sentinel=0" + NL +
                "    while IFS=$'\\t' read -r val desc; do" + NL +
                "        if [[ \"$val\" == \"__aesh_file__\" ]]; then" + NL +
                "            has_file_sentinel=1" + NL +
                "        elif [[ \"$val\" == \"__aesh_dir__\" ]]; then" + NL +
                "            has_dir_sentinel=1" + NL +
                "        else" + NL +
                "            completions+=(\"$val\")" + NL +
                "            if [[ -n \"$desc\" ]]; then" + NL +
                "                descriptions+=(\"$val:$desc\")" + NL +
                "            fi" + NL +
                "        fi" + NL +
                "    done < <(" + programName + " --aesh-complete -- \"${words[@]:1}\")" + NL +
                "    if (( ${#descriptions} > 0 )); then" + NL +
                "        _describe '' descriptions" + NL +
                "    elif (( ${#completions} > 0 )); then" + NL +
                "        compadd -a completions" + NL +
                "    fi" + NL +
                "    if (( has_file_sentinel )); then" + NL +
                "        _files" + NL +
                "    elif (( has_dir_sentinel )); then" + NL +
                "        _files -/" + NL +
                "    fi" + NL +
                "}" + NL +
                NL +
                "_" + programName + " \"$@\"" + NL;
    }

    private static String escapeZsh(String s) {
        if (s == null)
            return "";
        return s.replace("'", "'\\''")
                .replace("[", "\\[")
                .replace("]", "\\]")
                .replace(":", "\\:");
    }
}
