/*
 * JBoss, Home of Professional Open Source
 * Copyright 2014 Red Hat Inc. and/or its affiliates and other contributors
 * as indicated by the @authors tag
 * See the copyright.txt in the distribution for a
 * full listing of individual contributors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.aesh.command.activator;

import org.aesh.command.impl.internal.ParsedCommand;

/**
 * Decides whether a command is available at runtime.
 * <p>
 * When {@link #isActivated(ParsedCommand)} returns false the command is hidden
 * everywhere: it is rejected at execution time, excluded from interactive and
 * dynamic ({@code --aesh-complete}) completion, and excluded from the static
 * shell completion scripts generated by
 * {@link org.aesh.util.completer.ShellCompletionGenerator}.
 * <p>
 * This makes activators the recommended way to gate platform-conditional
 * commands (e.g. a macOS-only subcommand in a cross-platform CLI) behind a
 * single command tree:
 *
 * <pre>
 * public class MacOnly implements CommandActivator {
 *     public boolean isActivated(ParsedCommand command) {
 *         return Platform.isMacOS();
 *     }
 * }
 *
 * &#64;CommandDefinition(name = "vm", activator = MacOnly.class, ...)
 * public class VmCommand ... { }
 * </pre>
 *
 * Note the tradeoff: an activator hides the command at runtime but the class
 * still ships in the binary. If the code must be absent from a native-image
 * build entirely (dead-code elimination), register a separate top-level
 * command per platform instead and use
 * {@link org.aesh.util.completer.CompletionFilter} to keep generated
 * completions in step.
 *
 * @author Aesh team
 */
public interface CommandActivator {

    /**
     * Activates the current command to be "visible".
     * Eg: While completing commands this command will not be
     * displayed if this method return false.
     *
     * @return
     * @param command
     */
    boolean isActivated(ParsedCommand command);
}
