/*
 * JBoss, Home of Professional Open Source
 * Copyright 2014 Red Hat Inc. and/or its affiliates and other contributors
 * as indicated by the @authors tag. All rights reserved.
 * See the copyright.txt in the distribution for a
 * full listing of individual contributors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * http://www.apache.org/licenses/LICENSE-2.0
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.aesh.command.metadata;

import org.aesh.command.Command;
import org.aesh.command.impl.internal.ProcessedCommand;
import org.aesh.command.parser.CommandLineParserException;

/**
 * Provides compile-time generated metadata for a command class,
 * eliminating the need for runtime reflection to scan annotations.
 * <p>
 * Implementations are generated by the aesh-processor annotation processor
 * and discovered via {@link java.util.ServiceLoader}.
 *
 * @param <C> the command type
 * @author Aesh team
 */
public interface CommandMetadataProvider<C extends Command> {

    /**
     * @return the command class this provider handles
     */
    Class<C> commandType();

    /**
     * Create a new instance of the command without reflection.
     *
     * @return a new command instance
     */
    C newInstance();

    /**
     * Build the processed command metadata using literal values
     * extracted at compile time, avoiding annotation scanning at runtime.
     *
     * @param instance the command instance to attach to the metadata
     * @return the fully built ProcessedCommand
     * @throws CommandLineParserException if command metadata is invalid
     */
    @SuppressWarnings("rawtypes")
    ProcessedCommand buildProcessedCommand(C instance) throws CommandLineParserException;

    /**
     * @return true if this command is a group command with subcommands
     */
    boolean isGroupCommand();

    /**
     * @return the subcommand classes for a group command, empty array if not a group
     */
    Class<? extends Command>[] groupCommandClasses();

    /**
     * @return the command name as specified in the annotation, without building the full ProcessedCommand
     */
    String commandName();
}
