/*
 * JBoss, Home of Professional Open Source
 * Copyright 2014 Red Hat Inc. and/or its affiliates and other contributors
 * as indicated by the @authors tag. All rights reserved.
 * See the copyright.txt in the distribution for a
 * full listing of individual contributors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * http://www.apache.org/licenses/LICENSE-2.0
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.aesh.command.metadata;

/**
 * Registry that maps command class names to their generated
 * {@link CommandMetadataProvider} instances.
 * <p>
 * Implementations are generated by the aesh-processor annotation processor
 * (one per compilation unit) and discovered via {@link java.util.ServiceLoader}.
 * Each registry uses a {@code switch} statement for direct instantiation
 * of the requested provider — no reflection, no lambdas.
 * <p>
 * For projects with multiple modules, each module generates its own
 * registry. {@link MetadataProviderRegistry} queries all discovered
 * registries and caches the results.
 *
 * @author Aesh team
 */
public interface MetadataRegistry {

    /**
     * Look up a metadata provider by the command class's binary name.
     * <p>
     * The key must be the value returned by {@link Class#getName()},
     * e.g. {@code "com.example.MyCommand"} or {@code "com.example.Outer$Inner"}.
     *
     * @param commandClassName the binary name of the command class
     * @return the provider, or {@code null} if this registry does not handle the given class
     */
    CommandMetadataProvider<?> get(String commandClassName);
}
